### ISSUE TITLE
Trace Log Error

### ISSUE THREAD

**Issue by James112121** [Nexus-Mods/Nexus-Mod-Manager#1017]
I get this error everytime I try and load Nexus Mod Manager and click on Skyrim VR, I was wondering if anyone has encountered this before?.

Trace file has been created: TraceLog20200511142228.txt
Mod Manager Version: 0.70.11.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Witcher3: Supported
    Loading SkyrimVR: Supported
Determining Game Mode: (From Selection Form) SkyrimVR
Game Mode Factory Selected: Skyrim VR (SkyrimVR)
Creating Game Mode mutex (Attempt: 0)

Tracing an Unhandled Exception:
Exception: 
Message: 
	Could not find a part of the path 'C:\Users\Owner\Documents\My games\Skyrim VR\SkyrimVR.ini'.
Full Trace: 
	System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Owner\Documents\My games\Skyrim VR\SkyrimVR.ini'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Nexus.Client.Games.SkyrimVR.SkyrimVRGameMode..ctor(IEnvironmentInfo p_eifEnvironmentInfo, FileUtil p_futFileUtility)
   at Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory.InstantiateGameMode(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeFactory.BuildGameMode(FileUtil p_futFileUtility, ViewMessage& p_imsWarning)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Trace file has been created: TraceLog20200511142228.txt
Mod Manager Version: 0.70.11.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Witcher3: Supported
    Loading SkyrimVR: Supported
Determining Game Mode: (From Selection Form) SkyrimVR
Game Mode Factory Selected: Skyrim VR (SkyrimVR)
Creating Game Mode mutex (Attempt: 0)

Tracing an Unhandled Exception:
Exception: 
Message: 
	Could not find a part of the path 'C:\Users\Owner\Documents\My games\Skyrim VR\SkyrimVR.ini'.
Full Trace: 
	System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Owner\Documents\My games\Skyrim VR\SkyrimVR.ini'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Nexus.Client.Games.SkyrimVR.SkyrimVRGameMode..ctor(IEnvironmentInfo p_eifEnvironmentInfo, FileUtil p_futFileUtility)
   at Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory.InstantiateGameMode(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeFactory.BuildGameMode(FileUtil p_futFileUtility, ViewMessage& p_imsWarning)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Running Threads (1)

Tracing an Unhandled Exception:
Exception: 
Message: 
	The process cannot access the file 'C:\Users\Owner\Documents\Nexus Mod Manager\TraceLog20200511142228.txt' because it is being used by another process.
Full Trace: 
	System.IO.IOException: The process cannot access the file 'C:\Users\Owner\Documents\Nexus Mod Manager\TraceLog20200511142228.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)
   at Nexus.Client.HeaderlessTextWriterTraceListener.Flush()
   at System.Diagnostics.TraceInternal.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

**Comment by squid-box** [comment]
Looks like the core issue is `Could not find a part of the path 'C:\Users\Owner\Documents\My games\Skyrim VR\SkyrimVR.ini'.`

Does the file exist, and does NMM have access to it?

**Comment by James112121** [comment]
It does exist and how can I check if it has access to it?

**Comment by James112121** [comment]
Ok it now comes up with this as I have the game on steam 

Trace file has been created: TraceLog20200511164607.txt
Mod Manager Version: 0.70.11.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Witcher3: Supported
    Loading SkyrimVR: Supported
Determining Game Mode: (From Selection Form) SkyrimVR
Game Mode Factory Selected: Skyrim VR (SkyrimVR)
Creating Game Mode mutex (Attempt: 0)

Tracing an Unhandled Exception:
Exception: 
Message: 
	Could not find a part of the path 'C:\Users\Owner\Documents\My games\Skyrim VR\SkyrimVR.ini'.
Full Trace: 
	System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Owner\Documents\My games\Skyrim VR\SkyrimVR.ini'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Nexus.Client.Games.SkyrimVR.SkyrimVRGameMode..ctor(IEnvironmentInfo p_eifEnvironmentInfo, FileUtil p_futFileUtility)
   at Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory.InstantiateGameMode(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeFactory.BuildGameMode(FileUtil p_futFileUtility, ViewMessage& p_imsWarning)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Running Threads (1)
    3 () 
        Aborted

**Comment by James112121** [comment]
![7617beb7282f6946fbfdb82df77e4746](https://user-images.githubusercontent.com/45662255/81582096-877a9280-93a7-11ea-805d-d4cf7cd1abd2.png)


These are the files I have in the folder currently

**Comment by 67Thorne** [comment]
Had the same problem. We deleted ( had it Steam Backup from original download time... ) the entire folder, all links to NMM ( a pain at times... had to hunt... ), shut down the computer for a coffee break, rebooted, re-installed Steam Skyrim VR from saved Steam Recovery backup, did a VERIFY on the installation, waited for it to download some stupid 4kb file, rebooted again and everything worked fine. Don't forget to MANUALLY uninstall all your NMM Skyrim VR mods before doing the re-install. It's time consuming but sometimes better than pulling your hair out for days. That or just manually install mods until the NMM team figures things out. Good luck !!  ( yeah... still good that you reported the bug with screenshots.... )

**Comment by 67Thorne** [comment]
Oh yeah... one of the errors in your screenshot... XMLScript... HOW did you manage to get that DLL messed up? NMM uses the XML files for it's base information and installation dependancies... INFO.XML and I think it's called MODCONFIG.XML in the FOMOD folders of all GOOD mods for Vortex, NMM and ModManager to use. 

OUR Antivirus flagged a bunch of DLL files as unknown and flagged them for Cloud use only. We generally just tell our Antivirus program to ignore the ENTIRE NMM folder.  ( Trust me. My home network shared NMM folder is 16TB... yes... TERRABYTES large and having the antivirus go through ALL the zip folders would take forever when booting up the computers... )

Anyhow. You might have to MANUALLY re-download the NMM program and re-install it. Hopefully it wont invalidate all your installed mods and the XML error will fix itself.  Yeah. We're run into that problem a few times through the years.
