### ISSUE TITLE
TraceLog Error

### ISSUE THREAD

**Issue by HeadlessMatt** [Nexus-Mods/Nexus-Mod-Manager#1057]
Whenever I try to start NMM the Error box prompts up.

A Tace Log file was created at:
C:\Users\(my name)\OneDrive\Documents\Nexus Mod Manager\TraceLog20201002123109.txt

NMM Version up to date as of Oct 1, 2020 (I believe)

Trace file has been created: TraceLog20201002123748.txt
Mod Manager Version: 0.72.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Could not load file or assembly 'file:///D:\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
Full Trace: 
	System.BadImageFormatException: Could not load file or assembly 'file:///D:\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'file:///D:\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo environmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

File Name:	file:///D:\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll
Fusion Log:	WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

        Running Threads (0)

**Comment by squid-box** [comment]
It looks like the installation failed to install one or more dll's:

`Could not load file or assembly 'file:///D:\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll' or one of its dependencies.`

I would try to reinstall / install a newer version and see if that helps.
