### ISSUE TITLE
Unable to cast object of type 'System.String' to type 'Nexus.Client.ModManagement.ModProfile'

### ISSUE THREAD

**Issue by silajim** [Nexus-Mods/Nexus-Mod-Manager#1082]
Importing a mod backup gives out an exception.

I was importing a backup made on another pc that contained my Fallout 4 mods and this exception happened

Setting up listener on Nexus Mod Manager-Fallout4IpcServer/Fallout4Listener at 2020-12-30 17:37:41
Running Application.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Unable to cast object of type 'System.String' to type 'Nexus.Client.ModManagement.ModProfile'.
Full Trace: 
	System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Nexus.Client.ModManagement.ModProfile'.
   at Nexus.Client.MainForm.ViewModel_RestoringBackup(Object sender, EventArgs`1 e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Nexus.Client.MainFormVM.RestoreBackup(ModManagerControl p_mmgModManager)
   at Nexus.Client.Commands.Command.Execute()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: 0.72.3
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
Probably create a backup and apply it on another machine

**Additional information** 
```Trace file has been created: TraceLog20201230173736.txt
Mod Manager Version: 0.72.3.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: MonsterHunterWorld.dll
        Initializing: Nexus.Client.Games.MonsterHunterWorld.MonsterHunterWorldGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Fallout4: Supported
    Loading Fallout3: Supported
    Loading WorldOfTanks: Supported
Determining Game Mode: (From Selection Form) Fallout4
Game Mode Factory Selected: Fallout 4 (Fallout4)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Fallout 4 (Fallout4)
    Installation Path: D:\SteamLibrary\steamapps\common\Fallout 4
    Install Info Path: D:\Games\Nexus Mod Manager\Fallout4\Install Info
    Mod Path: D:\Games\Nexus Mod Manager\Fallout4\Mods
    Mod Cache Path: D:\Games\Nexus Mod Manager\Fallout4\Mods\cache
    Mod Download Cache: D:\Games\Nexus Mod Manager\Fallout4\Mods\downloads
    Overwrite Path: D:\Games\Nexus Mod Manager\Fallout4\Install Info\overwrites
    Virtual Install Path: D:\Games\Nexus Mod Manager\Fallout4\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\GameModes
            Checking: Fallout4.CSharpScript.dll
                Initializing: Nexus.Client.Games.Fallout4.Scripting.CSharpScript.Fallout4CSharpScriptType
            Checking: Fallout4.XmlScript.dll
                Initializing: Nexus.Client.Games.Fallout4.Scripting.XmlScript.Fallout4XmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Program Files\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: D:\Games\Nexus Mod Manager\Fallout4\Mods
    Found 0 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: D:\Games\Nexus Mod Manager\Fallout4\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: D:\SteamLibrary\steamapps\common\Fallout 4\Data
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\BostonFPSFixAIO.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\ClearReconScope.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Craftable Armor Size.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DD_Khassar_De_Templari_Increased_build.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLC items to manufacturing.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\FAR.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\FO4Hotkeys.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Green Commonwealth.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Homemaker - Unlocked Institute Objects.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\IncreasedSettlerPopulation50.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\ManufacturingExtended.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Movable Power Armor.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\mso_sms.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\RichMerchants.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\SaveManager.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scavver's Toolbox.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scientifically Plantable Trees.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap Everything - Core.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap-able Mods - AllinOne+DLC - Vanilla.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap-able Mods - CAS Patch - Vanilla.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\ScrapGrinder.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrapper Corpse Highlighting.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\SMH.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Spring in the Commonwealth.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\SSEX.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\StoreAllJunk_SeasonPassEdition.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\UncappedSettlementSurplus.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Unofficial Fallout 4 Patch.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\WorkshopSupplyRemover.esp
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCCoast.esm
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCNukaWorld.esm
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCRobot.esm
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop01.esm
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop02.esm
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop03.esm
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Fallout4.esm
                Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Homemaker.esm
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\BostonFPSFixAIO.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\ClearReconScope.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Craftable Armor Size.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DD_Khassar_De_Templari_Increased_build.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLC items to manufacturing.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\FAR.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\FO4Hotkeys.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Green Commonwealth.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Homemaker - Unlocked Institute Objects.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\IncreasedSettlerPopulation50.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\ManufacturingExtended.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Movable Power Armor.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\mso_sms.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\RichMerchants.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\SaveManager.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scavver's Toolbox.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scientifically Plantable Trees.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap Everything - Core.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap-able Mods - AllinOne+DLC - Vanilla.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap-able Mods - CAS Patch - Vanilla.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\ScrapGrinder.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrapper Corpse Highlighting.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\SMH.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Spring in the Commonwealth.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\SSEX.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\StoreAllJunk_SeasonPassEdition.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\UncappedSettlementSurplus.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Unofficial Fallout 4 Patch.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\WorkshopSupplyRemover.esp
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCCoast.esm
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCNukaWorld.esm
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCRobot.esm
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop01.esm
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop02.esm
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop03.esm
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Fallout4.esm
                Registered.
            Found: D:\SteamLibrary\steamapps\common\Fallout 4\Data\Homemaker.esm
                Registered.
        Found 37 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Fallout4.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCRobot.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop01.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCCoast.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop02.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop03.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCNukaWorld.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCRobot.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop01.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCCoast.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop02.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop03.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCNukaWorld.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Unofficial Fallout 4 Patch.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Homemaker.esm (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Green Commonwealth.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap Everything - Core.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrapper Corpse Highlighting.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\FAR.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\SaveManager.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\ClearReconScope.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\FO4Hotkeys.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Movable Power Armor.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\SSEX.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\SMH.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\StoreAllJunk_SeasonPassEdition.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\WorkshopSupplyRemover.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Spring in the Commonwealth.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\IncreasedSettlerPopulation50.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Craftable Armor Size.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap-able Mods - CAS Patch - Vanilla.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap-able Mods - AllinOne+DLC - Vanilla.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\ScrapGrinder.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scavver's Toolbox.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\ManufacturingExtended.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\mso_sms.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scientifically Plantable Trees.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\RichMerchants.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DD_Khassar_De_Templari_Increased_build.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\Homemaker - Unlocked Institute Objects.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLC items to manufacturing.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\UncappedSettlementSurplus.esp (IsNull=False)
            Loading D:\SteamLibrary\steamapps\common\Fallout 4\Data\BostonFPSFixAIO.esp (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: D:\SteamLibrary\steamapps\common\Fallout 4\Fallout4.exe (IsNull=False)
    SKSE Command: D:\SteamLibrary\steamapps\common\Fallout 4\f4se_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    LOOT Command:  (IsNull=True)
    FO4Edit Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
Loading Plugins into Plugin List: 37
    Loading: Fallout4.esm (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Fallout4.esm) (False)
    Loading: DLCRobot.esm (D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCRobot.esm) (False)
    Loading: DLCworkshop01.esm (D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop01.esm) (False)
    Loading: DLCCoast.esm (D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCCoast.esm) (False)
    Loading: DLCworkshop02.esm (D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop02.esm) (False)
    Loading: DLCworkshop03.esm (D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCworkshop03.esm) (False)
    Loading: DLCNukaWorld.esm (D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLCNukaWorld.esm) (False)
    Loading: Unofficial Fallout 4 Patch.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Unofficial Fallout 4 Patch.esp) (False)
    Loading: Homemaker.esm (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Homemaker.esm) (False)
    Loading: Green Commonwealth.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Green Commonwealth.esp) (False)
    Loading: Scrap Everything - Core.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap Everything - Core.esp) (False)
    Loading: Scrapper Corpse Highlighting.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrapper Corpse Highlighting.esp) (False)
    Loading: FAR.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\FAR.esp) (False)
    Loading: SaveManager.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\SaveManager.esp) (False)
    Loading: ClearReconScope.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\ClearReconScope.esp) (False)
    Loading: FO4Hotkeys.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\FO4Hotkeys.esp) (False)
    Loading: Movable Power Armor.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Movable Power Armor.esp) (False)
    Loading: SSEX.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\SSEX.esp) (False)
    Loading: SMH.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\SMH.esp) (False)
    Loading: StoreAllJunk_SeasonPassEdition.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\StoreAllJunk_SeasonPassEdition.esp) (False)
    Loading: WorkshopSupplyRemover.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\WorkshopSupplyRemover.esp) (False)
    Loading: Spring in the Commonwealth.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Spring in the Commonwealth.esp) (False)
    Loading: IncreasedSettlerPopulation50.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\IncreasedSettlerPopulation50.esp) (False)
    Loading: Craftable Armor Size.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Craftable Armor Size.esp) (False)
    Loading: Scrap-able Mods - CAS Patch - Vanilla.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap-able Mods - CAS Patch - Vanilla.esp) (False)
    Loading: Scrap-able Mods - AllinOne+DLC - Vanilla.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scrap-able Mods - AllinOne+DLC - Vanilla.esp) (False)
    Loading: ScrapGrinder.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\ScrapGrinder.esp) (False)
    Loading: Scavver's Toolbox.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scavver's Toolbox.esp) (False)
    Loading: ManufacturingExtended.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\ManufacturingExtended.esp) (False)
    Loading: mso_sms.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\mso_sms.esp) (False)
    Loading: Scientifically Plantable Trees.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Scientifically Plantable Trees.esp) (False)
    Loading: RichMerchants.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\RichMerchants.esp) (False)
    Loading: DD_Khassar_De_Templari_Increased_build.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\DD_Khassar_De_Templari_Increased_build.esp) (False)
    Loading: Homemaker - Unlocked Institute Objects.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\Homemaker - Unlocked Institute Objects.esp) (False)
    Loading: DLC items to manufacturing.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\DLC items to manufacturing.esp) (False)
    Loading: UncappedSettlementSurplus.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\UncappedSettlementSurplus.esp) (False)
    Loading: BostonFPSFixAIO.esp (D:\SteamLibrary\steamapps\common\Fallout 4\Data\BostonFPSFixAIO.esp) (False)
Setting up listener on Nexus Mod Manager-Fallout4IpcServer/Fallout4Listener at 2020-12-30 17:37:41
Running Application.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Unable to cast object of type 'System.String' to type 'Nexus.Client.ModManagement.ModProfile'.
Full Trace: 
	System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Nexus.Client.ModManagement.ModProfile'.
   at Nexus.Client.MainForm.ViewModel_RestoringBackup(Object sender, EventArgs`1 e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Nexus.Client.MainFormVM.RestoreBackup(ModManagerControl p_mmgModManager)
   at Nexus.Client.Commands.Command.Execute()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Running Threads (0)```

**Comment by DuskDweller** [comment]
Crash should be fixed in the next release.
