### ISSUE TITLE
Can't open NMM??

### ISSUE THREAD

**Issue by Seekertimo** [Nexus-Mods/Nexus-Mod-Manager#1116]
Tried to download mods today via NMM on nexus and it asked me to delete corrupted files so i did, ever since then i keep getting an error with logging in. Running as administator gives the same issue.

Tracefile says the following:

Trace file has been created: TraceLog20210325185937.txt
Mod Manager Version: 0.80.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: Cyberpunk2077.dll
        Initializing: Nexus.Client.Games.Cyberpunk2077.Cyberpunk2077GameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: MonsterHunterWorld.dll
        Initializing: Nexus.Client.Games.MonsterHunterWorld.MonsterHunterWorldGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Could not load file or assembly 'file:///C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
Full Trace: 
	System.BadImageFormatException: Could not load file or assembly 'file:///C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'file:///C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo environmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

File Name:	file:///C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll
Fusion Log:	WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

        Running Threads (0)

**Comment by DuskDweller** [comment]
Could not load file or assembly 'file:///C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll' or one of its dependencies. The module was expected to contain an assembly manifest.

Your NMM install is broken: first of all check whether Windows decided to block the NMM installer (right click on it, Properties, Unblock), then reinstall.
If you keep getting this issues then it's your antivirus blocking or removing dll files from the NMM install folder.
