### ISSUE TITLE
Trying to run NMM on my Macbook Pro M1. I'm simulating Windows 10 with parallels

### ISSUE THREAD

**Issue by HenThai** [Nexus-Mods/Nexus-Mod-Manager#1124]
Trace file has been created: TraceLog20210404125134.txt
Mod Manager Version: 0.80.4.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\NMM\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: Cyberpunk2077.dll
        Initializing: Nexus.Client.Games.Cyberpunk2077.Cyberpunk2077GameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\NMM\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\NMM\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\NMM\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load C:\Program Files\NMM\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: MonsterHunterWorld.dll
        Initializing: Nexus.Client.Games.MonsterHunterWorld.MonsterHunterWorldGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\NMM\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\NMM\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load C:\Program Files\NMM\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading SkyrimSE: Supported
Determining Game Mode: (From Selection Form) SkyrimSE
Game Mode Factory Selected: Skyrim Special Edition (SkyrimSE)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Skyrim Special Edition (SkyrimSE)
    Installation Path: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition
    Install Info Path: C:\Games\Nexus Mod Manager\SkyrimSE\Install Info
    Mod Path: C:\Games\Nexus Mod Manager\SkyrimSE\Mods
    Mod Cache Path: C:\Games\Nexus Mod Manager\SkyrimSE\Mods\cache
    Mod Download Cache: C:\Games\Nexus Mod Manager\SkyrimSE\Mods\downloads
    Overwrite Path: C:\Games\Nexus Mod Manager\SkyrimSE\Install Info\overwrites
    Virtual Install Path: C:\Games\Nexus Mod Manager\SkyrimSE\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Program Files\NMM\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Program Files\NMM\GameModes
            Checking: SkyrimSE.CSharpScript.dll
                Initializing: Nexus.Client.Games.SkyrimSE.Scripting.CSharpScript.SkyrimSECSharpScriptType
            Checking: SkyrimSE.XmlScript.dll
                Initializing: Nexus.Client.Games.SkyrimSE.Scripting.XmlScript.SkyrimSEXmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Program Files\NMM\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: C:\Games\Nexus Mod Manager\SkyrimSE\Mods
    Found 0 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: C:\Games\Nexus Mod Manager\SkyrimSE\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data
                Found: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Dawnguard.esm
                Found: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Dragonborn.esm
                Found: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\HearthFires.esm
                Found: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim.esm
                Found: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Update.esm
            Found: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Dawnguard.esm
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Dragonborn.esm
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\HearthFires.esm
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim.esm
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Update.esm
                Registered.
        Found 5 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Update.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Dawnguard.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\HearthFires.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Dragonborn.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Update.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Dawnguard.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\HearthFires.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Dragonborn.esm (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\SkyrimSE.exe (IsNull=False)
    SKSE Command: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\skse64_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command:  (IsNull=True)
    Wrye Bash Command:  (IsNull=False)
    SSEEdit Command:  (IsNull=False)
    SSEEditQuickAutoClean Command:  (IsNull=False)
    FNIS Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
    Dual Sheat Redux Patch Command:  (IsNull=False)
    Patchus Maximus Command:  (IsNull=False)
Loading Plugins into Plugin List: 5
    Loading: Skyrim.esm (C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim.esm) (False)
    Loading: Update.esm (C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Update.esm) (False)
    Loading: Dawnguard.esm (C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Dawnguard.esm) (False)
    Loading: HearthFires.esm (C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\HearthFires.esm) (False)
    Loading: Dragonborn.esm (C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Dragonborn.esm) (False)

Tracing an Unhandled Exception:
Exception: 
Message: 
	A generic error occurred in GDI+.
Full Trace: 
	System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height)
   at Nexus.Client.MainForm.UserStatusFeedback()
   at Nexus.Client.MainForm.InitializeDocuments()
   at Nexus.Client.MainForm.ResetUI()
   at Nexus.Client.MainForm..ctor(MainFormVM viewModel)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

Running Threads (0)

**Comment by DuskDweller** [comment]
Looks like the Windows 10 emulation is failing here:
System.Drawing.Graphics.DrawImage
