### ISSUE TITLE
NMM Error message trace log

### ISSUE THREAD

**Issue by elfthe** [Nexus-Mods/Nexus-Mod-Manager#1141]
Hi, I received an "Error" message from NMM from opening it, I have no idea how to fix the error.
Here's the trace log:

Tracing an Unhandled Exception:
Exception: 
Message: 
	This causes two bindings in the collection to bind to the same property.
Parameter name: binding
Full Trace: 
	System.ArgumentException: This causes two bindings in the collection to bind to the same property.
Parameter name: binding
   at System.Windows.Forms.ControlBindingsCollection.CheckDuplicates(Binding binding)
   at System.Windows.Forms.Binding.CheckBinding()
   at System.Windows.Forms.Binding.SetBindableComponent(IBindableComponent value)
   at System.Windows.Forms.ControlBindingsCollection.AddCore(Binding dataBinding)
   at System.Windows.Forms.BindingsCollection.Add(Binding binding)
   at Nexus.Client.Util.BindingHelper.CreateFullBinding[T,K](Control p_ctlControl, Expression`1 p_expControlProperty, Object p_objDataSource, Expression`1 p_expBoundProperty)
   at Nexus.Client.Settings.UI.DownloadSettingsPage.SetBindings(DownloadSettingsGroup downloadSettingsGroup)
   at Nexus.Client.Settings.UI.DownloadSettingsPage.dsgSettings_UpdatedSettings(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Nexus.Client.ModRepositories.NexusModsApiRepository.set_UserStatus(User value)
   at Nexus.Client.ModRepositories.NexusModsApiRepository.Authenticate()
   at Nexus.Client.SSO.AuthenticationFormTask.TokenLogin()
   at Nexus.Client.SSO.AuthenticationFormTask.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

[nxm://skyrimspecialedition/mods/42032/files/174086?key=B-NUsXSm7J2TrSg_qwRQoQ&expires=1619274150&user_id=91400788] Starting Add Mod Task.
[nxm://skyrimspecialedition/mods/42032/files/174086?key=B-NUsXSm7J2TrSg_qwRQoQ&expires=1619274150&user_id=91400788] Downloading Files.
[nxm://skyrimspecialedition/mods/42032/files/174086?key=B-NUsXSm7J2TrSg_qwRQoQ&expires=1619274150&user_id=91400788] Launching downloading of https://files.nexus-cdn.com/1704/42032/Cathedral - 3D Pine Grass - Full 3D Coverage-42032-0-462-1607622295.7z?md5=wTLIsP_UXl_IErz3fVnQMQ&expires=1619115817&user_id=91400788.
[https://files.nexus-cdn.com/1704/42032/Cathedral - 3D Pine Grass - Full 3D Coverage-42032-0-462-1607622295.7z?md5=wTLIsP_UXl_IErz3fVnQMQ&expires=1619115817&user_id=91400788] Retrieving meta data.
[https://files.nexus-cdn.com/1704/42032/Cathedral - 3D Pine Grass - Full 3D Coverage-42032-0-462-1607622295.7z?md5=wTLIsP_UXl_IErz3fVnQMQ&expires=1619115817&user_id=91400788] Downloading.
[C:\Games\Nexus Mod Manager\SkyrimSE\Mods\downloads\Cathedral - 3D Pine Grass - Full 3D Coverage-42032-0-462-1607622295.7z] Adding mod from archive.
Running Threads (1)
    6 () 
        Aborted

I will be grateful if you have found the solution, thanks & bye.

**Comment by DuskDweller** [comment]
Do you always get this crash ?

**Comment by elfthe** [comment]
No, I don't, but sorry for wasting everybody time's here, I tried the mod & everything seems fine but didn't like it anyway so I uninstalled it, I was just anxious about that error message that's it, and again I'm terribly sorry for wasting your time.

**Comment by elfthe** [comment]
> 
> 
> Do you always get this crash ?

No, I don't, but sorry for wasting everybody time's here, I tried the mod & everything seems fine but didn't like it anyway so I uninstalled it, I was just anxious about that error message that's it, and again I'm terribly sorry for wasting your time.
