### ISSUE TITLE
Keep receiving this error upon trying to login via Nexus program

### ISSUE THREAD

**Issue by iLLMAGICxKiNG** [Nexus-Mods/Nexus-Mod-Manager#122]
I am pretty much out of ideas. I've reinstalled multiple times, reinstalled the games, deleted Nexus, etc.

> See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.BadImageFormatException: Could not load file or assembly 'System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Nexus.Client.ModRepositories.Nexus.NexusModRepository.GetProxyFactory(Boolean p_booIsGatekeeper)
   at Nexus.Client.ModRepositories.Nexus.NexusModRepository.Login(String p_strUsername, String p_strPassword, Dictionary`2& p_dicTokens)
   at Nexus.Client.LoginFormVM.Login()
   at Nexus.Client.LoginFormTask.LoginForm_Authenticating(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Nexus.Client.LoginForm.butLogin_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NexusClient
    Assembly Version: 0.63.14.0
    Win32 Version: 0.63.14.0
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/NexusClient.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2093.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2094.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NexusClient.Interface
    Assembly Version: 1.1.6310.19282
    Win32 Version: 1.1.6310.19282
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/NexusClient.Interface.DLL
----------------------------------------
SevenZipSharp
    Assembly Version: 0.64.3890.29348
    Win32 Version: 0.64.3890.29348
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/SevenZipSharp.DLL
----------------------------------------
Util
    Assembly Version: 1.1.6296.22671
    Win32 Version: 1.1.6296.22671
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/Util.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
UI
    Assembly Version: 1.1.6296.22671
    Win32 Version: 1.1.6296.22671
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/UI.DLL
----------------------------------------
ModManager.Interface
    Assembly Version: 1.1.6310.19282
    Win32 Version: 1.1.6310.19282
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/ModManager.Interface.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
BreakingWheel
    Assembly Version: 1.1.6310.19285
    Win32 Version: 1.1.6310.19285
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/BreakingWheel.dll
----------------------------------------
ChinhDo.Transactions
    Assembly Version: 1.1.0.25
    Win32 Version: 1.1.0.25
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/ChinhDo.Transactions.DLL
----------------------------------------
DarkSouls
    Assembly Version: 1.1.6310.19283
    Win32 Version: 1.1.6310.19283
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DarkSouls.dll
----------------------------------------
DarkSouls2
    Assembly Version: 1.1.6310.19284
    Win32 Version: 1.1.6310.19284
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DarkSouls2.dll
----------------------------------------
DragonAge
    Assembly Version: 1.1.6310.19283
    Win32 Version: 1.1.6310.19283
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DragonAge.dll
----------------------------------------
DragonAge2
    Assembly Version: 1.1.6310.19283
    Win32 Version: 1.1.6310.19283
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DragonAge2.dll
----------------------------------------
DragonsDogma
    Assembly Version: 1.1.6310.19285
    Win32 Version: 1.1.6310.19285
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DragonsDogma.dll
----------------------------------------
Fallout3.CSharpScript
    Assembly Version: 1.1.6310.19287
    Win32 Version: 1.1.6310.19287
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout3.CSharpScript.dll
----------------------------------------
Fallout3
    Assembly Version: 1.1.6310.19285
    Win32 Version: 1.1.6310.19285
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout3.dll
----------------------------------------
GamebryoBase
    Assembly Version: 1.1.6310.19283
    Win32 Version: 1.1.6310.19283
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/GamebryoBase.DLL
----------------------------------------
Commanding
    Assembly Version: 1.1.6310.19282
    Win32 Version: 1.1.6310.19282
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/Commanding.DLL
----------------------------------------
Fallout3.XmlScript
    Assembly Version: 1.1.6310.19287
    Win32 Version: 1.1.6310.19287
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout3.XmlScript.dll
----------------------------------------
Fallout4.CSharpScript
    Assembly Version: 1.1.6310.19288
    Win32 Version: 1.1.6310.19288
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout4.CSharpScript.dll
----------------------------------------
Fallout4
    Assembly Version: 1.1.6310.19287
    Win32 Version: 1.1.6310.19287
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout4.dll
----------------------------------------
Fallout4.XmlScript
    Assembly Version: 1.1.6310.19288
    Win32 Version: 1.1.6310.19288
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout4.XmlScript.dll
----------------------------------------
FalloutNV.CSharpScript
    Assembly Version: 1.1.6310.19287
    Win32 Version: 1.1.6310.19287
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/FalloutNV.CSharpScript.dll
----------------------------------------
FalloutNV
    Assembly Version: 1.1.6310.19286
    Win32 Version: 1.1.6310.19286
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/FalloutNV.dll
----------------------------------------
FalloutNV.XmlScript
    Assembly Version: 1.1.6310.19289
    Win32 Version: 1.1.6310.19289
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/FalloutNV.XmlScript.dll
----------------------------------------
Grimrock
    Assembly Version: 1.1.6310.19283
    Win32 Version: 1.1.6310.19283
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Grimrock.dll
----------------------------------------
Morrowind
    Assembly Version: 1.1.6310.19285
    Win32 Version: 1.1.6310.19285
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Morrowind.dll
----------------------------------------
Morrowind.ModScript
    Assembly Version: 1.1.6310.19286
    Win32 Version: 1.1.6310.19286
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Morrowind.ModScript.dll
----------------------------------------
NoMansSky
    Assembly Version: 1.1.6310.19292
    Win32 Version: 1.1.6310.19292
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/NoMansSky.dll
----------------------------------------
Oblivion
    Assembly Version: 1.1.6310.19285
    Win32 Version: 1.1.6310.19285
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Oblivion.dll
----------------------------------------
Oblivion.ModScript
    Assembly Version: 1.1.6310.19286
    Win32 Version: 1.1.6310.19286
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Oblivion.ModScript.dll
----------------------------------------
Skyrim.CSharpScript
    Assembly Version: 1.1.6310.19289
    Win32 Version: 1.1.6310.19289
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Skyrim.CSharpScript.dll
----------------------------------------
Skyrim
    Assembly Version: 1.1.6310.19287
    Win32 Version: 1.1.6310.19287
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Skyrim.dll
----------------------------------------
Skyrim.XmlScript
    Assembly Version: 1.1.6310.19289
    Win32 Version: 1.1.6310.19289
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Skyrim.XmlScript.dll
----------------------------------------
SkyrimSE.CSharpScript
    Assembly Version: 1.1.6310.19288
    Win32 Version: 1.1.6310.19288
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/SkyrimSE.CSharpScript.dll
----------------------------------------
SkyrimSE
    Assembly Version: 1.1.6310.19287
    Win32 Version: 1.1.6310.19287
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/SkyrimSE.dll
----------------------------------------
SkyrimSE.XmlScript
    Assembly Version: 1.1.6310.19289
    Win32 Version: 1.1.6310.19289
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/SkyrimSE.XmlScript.dll
----------------------------------------
Starbound
    Assembly Version: 1.1.6310.19284
    Win32 Version: 1.1.6310.19284
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Starbound.dll
----------------------------------------
StateOfDecay
    Assembly Version: 1.1.6310.19292
    Win32 Version: 1.1.6310.19292
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/StateOfDecay.dll
----------------------------------------
TESO
    Assembly Version: 1.1.6310.19284
    Win32 Version: 1.1.6310.19284
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/TESO.dll
----------------------------------------
WarThunder
    Assembly Version: 1.1.6310.19285
    Win32 Version: 1.1.6310.19285
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/WarThunder.dll
----------------------------------------
Witcher2
    Assembly Version: 1.1.6310.19283
    Win32 Version: 1.1.6310.19283
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Witcher2.dll
----------------------------------------
Witcher3
    Assembly Version: 1.1.6310.19285
    Win32 Version: 1.1.6310.19285
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Witcher3.dll
----------------------------------------
WorldOfTanks
    Assembly Version: 1.1.6310.19283
    Win32 Version: 1.1.6310.19283
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/WorldOfTanks.dll
----------------------------------------
XCOM2
    Assembly Version: 1.1.5975.32869
    Win32 Version: 1.1.5975.32869
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/XCOM2.dll
----------------------------------------
XRebirth
    Assembly Version: 1.1.6310.19284
    Win32 Version: 1.1.6310.19284
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/GameModes/XRebirth.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Scripting
    Assembly Version: 1.1.6310.19282
    Win32 Version: 1.1.6310.19282
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/Scripting.DLL
----------------------------------------
Mods
    Assembly Version: 1.1.6310.19282
    Win32 Version: 1.1.6310.19282
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/Mods.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Antlr3.Runtime
    Assembly Version: 3.4.1.9004
    Win32 Version: 3.4.1.9004
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/Antlr3.Runtime.dll
----------------------------------------
AntlrUtil
    Assembly Version: 1.1.6310.19282
    Win32 Version: 1.1.6310.19282
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/AntlrUtil.dll
----------------------------------------
CSharpScript
    Assembly Version: 1.1.6310.19283
    Win32 Version: 1.1.6310.19283
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/CSharpScript.dll
----------------------------------------
ModScript
    Assembly Version: 1.1.6310.19284
    Win32 Version: 1.1.6310.19284
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/ModScript.dll
----------------------------------------
XmlScript
    Assembly Version: 1.1.6310.19284
    Win32 Version: 1.1.6310.19284
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/XmlScript.dll
----------------------------------------
ICSharpCode.TextEditor
    Assembly Version: 3.2.1.6466
    Win32 Version: 3.2.1.6466
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/ICSharpCode.TextEditor.DLL
----------------------------------------
FOMod
    Assembly Version: 1.1.6310.19283
    Win32 Version: 1.1.6310.19283
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/ModFormats/FOMod.dll
----------------------------------------
Transactions
    Assembly Version: 1.1.6296.22671
    Win32 Version: 1.1.6296.22671
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/Transactions.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.17873
    Win32 Version: 2.9.1.0
    CodeBase: file:///F:/Program%20Files/Nexus%20Mod%20Manager/ObjectListView.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by illmaticxking** [comment]
I reinstalled my OS (Windows 10) after thinking it had to do with a corrupt version of .net framework, but I am still receiving this error. I believe it is on Nexus' side considering I've done everything including reinstalling my OS.

Any other ideas?

**Comment by illmaticxking** [comment]
For anyone curious, I was able to solve this.

Basically:

C: > Windows > Microsoft.NET > Framework > v2,0.50727  was missing file "System.Web.Extensions.dll".

Open C: > Program Files > Reference Assemblies > Microsoft > Framework > v3.5 and copy "System.Web.Extensions.dll" and paste it in the v2.0.50727 folder.

**Comment by squid-box** [comment]
To me this looks like something is wrong with your .NET installation. The fact that NMM isn't able to find/use System.ServiceModel.Web makes me doubt this is anything on the NMM side of things.

By now this version of NMM is pretty outdated, are you having the same issues with [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9)?

If so, are you getting any trace log files?

**Comment by squid-box** [comment]
Closing issue due to inactivity.
