### ISSUE TITLE
nexus keeps sending me an error when i try to install a mod

### ISSUE THREAD

**Issue by Taragoembi** [Nexus-Mods/Nexus-Mod-Manager#1226]
C\:Users/Taragoem/OneDrive/Documents/Nexus Mod Manager/TraceLog20220723191134.txt

The Following information is in the Trace Log: - Exception: - Message: - he cloud file provider is not running
Full Trace: System.IO.IOException: The cloud file provider is not running
at System.IO.___Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
at System.IO.FileStream.Read(Byte[] Array, Int32 offset, Int32 count)
at System.IO.StreamReader.ReadBuffer()
at System.IO.StreamReader.ReadLine()
at Nexus.Client.Games.Fallout4.Tools.GamebryoIniReader.set_IniFile(String value
at Nexus.Client.Games.Fallout4.Fallout4GameMode.RequiresExternalConfig(String&P_strMessage
at Nexus.Client.ModManagement.UI.ModManagerVM.ActivateMods(List'1 P_IstMod)
at Nexus.Client.Commands.Generic.Command'1.Execute(T p_tArgument)
at Nexus.Client.Commands. Genetic.CommandBinding'1.Execute()
at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
at System.Windows.Forms.ToolStripItem.HandleClick(eventArgs e)
at System.Windows.Forms.ToolStripItem.HandleMouseUp(MoseEventArgs e)
at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
at System.Windows.Forms.Conrtol.WmMouseUp(Message& m, MouseButtons button, Int32 clicks
at System.Windows.Forms.Control.WndProc(message& m)
at System.Windows.Forms.ToolStrip.WndProc(MEssage& m)
at System.Windows.Forms.Native Window.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam

Whenever i try to install a mod it sends me a "Nexus Mod Manager has encountered an error and needs to close" error

**Environment**
- NMM version: _0.83.6_
I do not have any mods installed as it wont allow me to

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by TheArcaneBrony** [comment]
Its throwing an exception about onedrive, did you stop onedrive running in the background?

**Comment by Taragoembi** [comment]
I did but I stopped running it a long time ago

> Its throwing an exception about onedrive, did you stop onedrive running in the background?
