### ISSUE TITLE
BG3 84.8.0 BUG

### ISSUE THREAD

**Issue by jpee1965** [Nexus-Mods/Nexus-Mod-Manager#1293]
Can't install BG3-
NMM can find the game but it selects the LAUNCHER folder for exe not the BIN folder which is where the exe is found.

![image](https://github.com/Nexus-Mods/Nexus-Mod-Manager/assets/142131995/535d460e-c52b-477f-bb7b-1dfe59b4e6ad)

![image](https://github.com/Nexus-Mods/Nexus-Mod-Manager/assets/142131995/aeeb83c0-6c56-499a-874f-98c22b1c3f24)

![image](https://github.com/Nexus-Mods/Nexus-Mod-Manager/assets/142131995/1b8ad016-5439-487b-b48e-4717ef320400)

![image](https://github.com/Nexus-Mods/Nexus-Mod-Manager/assets/142131995/1f3aecf0-568f-4108-8f8d-c8e847e9ecc7)

NMM will **not** recognize D:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin  as where the EXE resides . Cannot browse to it therefore NMM crashes when attempting to setup.

**Comment by jpee1965** [comment]
[TraceLog20230812225530.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/12328776/TraceLog20230812225530.txt)

Trace file has been created: TraceLog20230812225530.txt
Mod Manager Version: 0.84.8.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BaldursGate3.dll
        Initializing: Nexus.Client.Games.BaldursGate3.BaldursGate3GameModeFactory
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: Cyberpunk2077.dll
        Initializing: Nexus.Client.Games.Cyberpunk2077.Cyberpunk2077GameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: EnderalSE.dll
        Initializing: Nexus.Client.Games.EnderalSE.EnderalSEGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: HogwartsLegacy.dll
        Initializing: Nexus.Client.Games.HogwartsLegacy.HogwartsLegacyGameModeFactory
    Checking: ModScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: MonsterHunterWorld.dll
        Initializing: Nexus.Client.Games.MonsterHunterWorld.MonsterHunterWorldGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: MountAndBlade2Bannerlord.dll
        Initializing: Nexus.Client.Games.MountAndBlade2Bannerlord.MountAndBlade2BannerlordGameModeFactory
    Checking: Newtonsoft.Json.dll
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Sims4.dll
        Initializing: Nexus.Client.Games.Sims4.Sims4GameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimGOG.CSharpScript.dll
    Checking: SkyrimGOG.dll
        Initializing: Nexus.Client.Games.SkyrimGOG.SkyrimGOGGameModeFactory
    Checking: SkyrimGOG.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\SkyrimGOG.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StardewValley.dll
        Initializing: Nexus.Client.Games.StardewValley.StardewValleyGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: Subnautica.dll
        Initializing: Nexus.Client.Games.Subnautica.SubnauticaGameModeFactory
    Checking: SubnauticaBelowZero.dll
        Initializing: Nexus.Client.Games.SubnauticaBelowZero.SubnauticaBelowZeroGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading BaldursGate3: Supported
    Loading Skyrim: Supported
    Loading Fallout4: Supported
Determining Game Mode: (From Selection Form) BaldursGate3
Game Mode Factory Selected: Baldur's Gate 3 (BaldursGate3)
Creating Game Mode mutex (Attempt: 0)

Tracing an Unhandled Exception:
Exception: 
Message: 
	The path is not of a legal form.
Full Trace: 
	System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetPathRoot(String path)
   at Nexus.Client.Games.Settings.SetupDirectoriesControlVM.CheckOnGameHD(String p_strPath)
   at Nexus.Client.Games.Settings.SetupDirectoriesControlVM.LoadSettings()
   at Nexus.Client.Games.Settings.SetupDirectoriesControl.set_ViewModel(SetupDirectoriesControlVM value)
   at Nexus.Client.Games.BaldursGate3.SetupForm.set_ViewModel(SetupBaseVM value)
   at Nexus.Client.Games.BaldursGate3.BaldursGate3GameModeFactory.PerformInitialSetup(ShowViewDelegate p_dlgShowView, ShowMessageDelegate p_dlgShowMessage)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Trace file has been created: TraceLog20230812225530.txt
Mod Manager Version: 0.84.8.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BaldursGate3.dll
        Initializing: Nexus.Client.Games.BaldursGate3.BaldursGate3GameModeFactory
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: Cyberpunk2077.dll
        Initializing: Nexus.Client.Games.Cyberpunk2077.Cyberpunk2077GameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: EnderalSE.dll
        Initializing: Nexus.Client.Games.EnderalSE.EnderalSEGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: HogwartsLegacy.dll
        Initializing: Nexus.Client.Games.HogwartsLegacy.HogwartsLegacyGameModeFactory
    Checking: ModScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: MonsterHunterWorld.dll
        Initializing: Nexus.Client.Games.MonsterHunterWorld.MonsterHunterWorldGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: MountAndBlade2Bannerlord.dll
        Initializing: Nexus.Client.Games.MountAndBlade2Bannerlord.MountAndBlade2BannerlordGameModeFactory
    Checking: Newtonsoft.Json.dll
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Sims4.dll
        Initializing: Nexus.Client.Games.Sims4.Sims4GameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimGOG.CSharpScript.dll
    Checking: SkyrimGOG.dll
        Initializing: Nexus.Client.Games.SkyrimGOG.SkyrimGOGGameModeFactory
    Checking: SkyrimGOG.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\SkyrimGOG.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StardewValley.dll
        Initializing: Nexus.Client.Games.StardewValley.StardewValleyGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: Subnautica.dll
        Initializing: Nexus.Client.Games.Subnautica.SubnauticaGameModeFactory
    Checking: SubnauticaBelowZero.dll
        Initializing: Nexus.Client.Games.SubnauticaBelowZero.SubnauticaBelowZeroGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading BaldursGate3: Supported
    Loading Skyrim: Supported
    Loading Fallout4: Supported
Determining Game Mode: (From Selection Form) BaldursGate3
Game Mode Factory Selected: Baldur's Gate 3 (BaldursGate3)
Creating Game Mode mutex (Attempt: 0)

Tracing an Unhandled Exception:
Exception: 
Message: 
	The path is not of a legal form.
Full Trace: 
	System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetPathRoot(String path)
   at Nexus.Client.Games.Settings.SetupDirectoriesControlVM.CheckOnGameHD(String p_strPath)
   at Nexus.Client.Games.Settings.SetupDirectoriesControlVM.LoadSettings()
   at Nexus.Client.Games.Settings.SetupDirectoriesControl.set_ViewModel(SetupDirectoriesControlVM value)
   at Nexus.Client.Games.BaldursGate3.SetupForm.set_ViewModel(SetupBaseVM value)
   at Nexus.Client.Games.BaldursGate3.BaldursGate3GameModeFactory.PerformInitialSetup(ShowViewDelegate p_dlgShowView, ShowMessageDelegate p_dlgShowMessage)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Running Threads (1)
    4 () 
        Aborted

**Comment by mitsoswu** [comment]
Hmmm, hey wait a minute.... You are NOT supose to install games into the Program Files (x86) folder. 
 Why ? Because it will give you problems. This is a folder programed to be protected by windows. Many people have 
 reported this years ago. 
 But you can right-click on the C drive if you like and create, a new folder. And you can name it whatever you like.
 For example: "Other games" or "my special folder" or something..
 
 I hope this helps.

**Comment by TylerCode** [comment]
Idk, steam by default will put things in program files. That's what the folder is for, program files. 

I would certainly consider this a bug. 

Try Browse while running NMM as admin and it will allow you access to the folder. However, it may not be a problem with which executable is being selected. I haven't looked at the BG3 implementation at all.

**Comment by mitsoswu** [comment]
Yes i know about "Steam" default folder. I guess you didn't notice that Steam also gives you the abilty, to set or install your games in different folders as well, or even in different Drives. 

For example:  i install all of my games on D drive with no problem. On Program Files x86 in C drive, usually go other programs, i leave them as is. 
BUT when it comes to **games** (and of course these games can be **moded**) then, windows defender doesn't know if your "Mod" is harmfull or not.... sometime it deletes them and you then have problems and your game isn't working correctly, you know what i mean?

**Comment by TylerCode** [comment]
For sure, I'm not saying that moving it out of Program Files is wrong or bad, I'm making the argument that the application should be able to handle that since that is technically what that folder is for. (I fully blame windows for this though)

Also, someone who knows to make an alternate library for steam because of issues with windows is also likely to know how to work around those issues. At the very least NMM should alert the user to move the game, or ideally, should know if it doesn't have permissions to a folder and then ask for a privilege escalation so that it can perform its duties.
