### ISSUE TITLE
My NMM wont launch

### ISSUE THREAD

**Issue by Tragicll** [Nexus-Mods/Nexus-Mod-Manager#1302]
Trace file has been created: TraceLog20231028231042.txt
Mod Manager Version: 0.84.9.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Steam\steamapps\common\Skyrim Special Edition\NMM\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BaldursGate3.dll
        Initializing: Nexus.Client.Games.BaldursGate3.BaldursGate3GameModeFactory
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: Cyberpunk2077.dll
        Initializing: Nexus.Client.Games.Cyberpunk2077.Cyberpunk2077GameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Could not load file or assembly 'file:///D:\Steam\steamapps\common\Skyrim Special Edition\NMM\GameModes\DragonAge2.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
Full Trace: 
	System.BadImageFormatException: Could not load file or assembly 'file:///D:\Steam\steamapps\common\Skyrim Special Edition\NMM\GameModes\DragonAge2.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'file:///D:\Steam\steamapps\common\Skyrim Special Edition\NMM\GameModes\DragonAge2.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo environmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

File Name:	file:///D:\Steam\steamapps\common\Skyrim Special Edition\NMM\GameModes\DragonAge2.dll
Fusion Log:	WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

        Running Threads (0)

**Comment by TylerCode** [comment]
Just wanted to confirm a few things here. Are you on Windows 8? Crash log may be reporting incorrectly.
