### ISSUE TITLE
NMM won't open, after updating it

### ISSUE THREAD

**Issue by Pentarosa** [Nexus-Mods/Nexus-Mod-Manager#1315]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_ NMM wouldn't open after updating it. The error was gibberish to me as I'm not a coder. I've tried following the instructions so hopefully you can help me...?

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

Trace file has been created: TraceLog20240213142407.txt
Mod Manager Version: 0.70.5.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BaldursGate3.dll
        Initializing: Nexus.Client.Games.BaldursGate3.BaldursGate3GameModeFactory
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: Cyberpunk2077.dll
        Initializing: Nexus.Client.Games.Cyberpunk2077.Cyberpunk2077GameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: EnderalSE.dll
        Initializing: Nexus.Client.Games.EnderalSE.EnderalSEGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: HogwartsLegacy.dll
        Initializing: Nexus.Client.Games.HogwartsLegacy.HogwartsLegacyGameModeFactory
    Checking: ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: MonsterHunterWorld.dll
        Initializing: Nexus.Client.Games.MonsterHunterWorld.MonsterHunterWorldGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: Morrowind.ModScript.dll
    Checking: MountAndBlade2Bannerlord.dll
        Initializing: Nexus.Client.Games.MountAndBlade2Bannerlord.MountAndBlade2BannerlordGameModeFactory
    Checking: Newtonsoft.Json.dll
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Oblivion.ModScript.dll
    Checking: Sims4.dll
        Initializing: Nexus.Client.Games.Sims4.Sims4GameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimGOG.CSharpScript.dll
    Checking: SkyrimGOG.dll
        Initializing: Nexus.Client.Games.SkyrimGOG.SkyrimGOGGameModeFactory
    Checking: SkyrimGOG.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimGOG.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StardewValley.dll
        Initializing: Nexus.Client.Games.StardewValley.StardewValleyGameModeFactory
    Checking: Starfield.dll
        Initializing: Nexus.Client.Games.Starfield.StarfieldGameModeFactory
    Checking: Starfield.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Starfield.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: Subnautica.dll
        Initializing: Nexus.Client.Games.Subnautica.SubnauticaGameModeFactory
    Checking: SubnauticaBelowZero.dll
        Initializing: Nexus.Client.Games.SubnauticaBelowZero.SubnauticaBelowZeroGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Fallout4: Supported
Determining Game Mode: (From Selection Form) Fallout4
Game Mode Factory Selected: Fallout 4 (Fallout4)
Creating Game Mode mutex (Attempt: 0)

Tracing an Unhandled Exception:
Running Threads (1)
    3 () 
        Aborted
        Exception: 
Message: 
	Method 'add_ActivePluginUpdate' in type 'Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.PluginOrderManager' from assembly 'GamebryoBase, Version=0.86.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Full Trace: 
	System.TypeLoadException: Method 'add_ActivePluginUpdate' in type 'Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.PluginOrderManager' from assembly 'GamebryoBase, Version=0.86.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeBase.SetupPluginManagement(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Fallout4.Fallout4GameMode..ctor(IEnvironmentInfo p_eifEnvironmentInfo, FileUtil p_futFileUtility)
   at Nexus.Client.Games.Fallout4.Fallout4GameModeFactory.InstantiateGameMode(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeFactory.BuildGameMode(FileUtil p_futFileUtility, ViewMessage& p_imsWarning)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by Pentarosa** [comment]
To reproduce the problem, all I have to do is try to opoen NMM
