### ISSUE TITLE
[0.63.11] Unhandled Exception

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [Nexus-Mods/Nexus-Mod-Manager#24]
![2017-01-09](https://cloud.githubusercontent.com/assets/18717349/21767901/a06b891c-d644-11e6-8ed1-e76de4eb00d3.png)

I got this error while trying to log in. Below this I am leaving all of the details that was on the error message:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.BadImageFormatException: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' ---> System.BadImageFormatException: [C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll] A valid typedef or typeref token is expected to follow a ELEMENT_TYPE_CLASS or ELEMENT_TYPE_VALUETYPE.
   at System.ServiceModel.Description.ConfigLoader.LoadIdentity(IdentityElement element)
   at System.ServiceModel.Description.ConfigLoader.LoadChannelBehaviors(ServiceEndpoint serviceEndpoint, String configurationName)
   at System.ServiceModel.ChannelFactory.ApplyConfiguration(String configurationName, Configuration configuration)
   at System.ServiceModel.ChannelFactory.InitializeEndpoint(String configurationName, EndpointAddress address)
   at System.ServiceModel.ChannelFactory`1..ctor(String endpointConfigurationName, EndpointAddress remoteAddress)
   at Nexus.Client.ModRepositories.Nexus.NexusModRepository.GetProxyFactory(Boolean p_booIsGatekeeper)
   at Nexus.Client.ModRepositories.Nexus.NexusModRepository.Login(String p_strUsername, String p_strPassword, Dictionary`2& p_dicTokens)
   at Nexus.Client.LoginFormVM.Login()
   at Nexus.Client.LoginFormTask.LoginForm_Authenticating(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Nexus.Client.LoginForm.butLogin_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NexusClient
    Assembly Version: 0.63.11.0
    Win32 Version: 0.63.11.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/NexusClient.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NexusClient.Interface
    Assembly Version: 1.1.6200.23533
    Win32 Version: 1.1.6200.23533
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/NexusClient.Interface.DLL
----------------------------------------
SevenZipSharp
    Assembly Version: 0.64.3890.29348
    Win32 Version: 0.64.3890.29348
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/SevenZipSharp.DLL
----------------------------------------
Util
    Assembly Version: 1.1.6185.26943
    Win32 Version: 1.1.6185.26943
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/Util.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
UI
    Assembly Version: 1.1.6185.26944
    Win32 Version: 1.1.6185.26944
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/UI.DLL
----------------------------------------
ModManager.Interface
    Assembly Version: 1.1.6200.23533
    Win32 Version: 1.1.6200.23533
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ModManager.Interface.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
BreakingWheel
    Assembly Version: 1.1.6200.23535
    Win32 Version: 1.1.6200.23535
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/BreakingWheel.dll
----------------------------------------
ChinhDo.Transactions
    Assembly Version: 1.1.0.25
    Win32 Version: 1.1.0.25
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ChinhDo.Transactions.DLL
----------------------------------------
DarkSouls
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DarkSouls.dll
----------------------------------------
DarkSouls2
    Assembly Version: 1.1.6200.23535
    Win32 Version: 1.1.6200.23535
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DarkSouls2.dll
----------------------------------------
DragonAge
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DragonAge.dll
----------------------------------------
DragonAge2
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DragonAge2.dll
----------------------------------------
DragonsDogma
    Assembly Version: 1.1.6200.23535
    Win32 Version: 1.1.6200.23535
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DragonsDogma.dll
----------------------------------------
Fallout3.CSharpScript
    Assembly Version: 1.1.6200.23536
    Win32 Version: 1.1.6200.23536
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout3.CSharpScript.dll
----------------------------------------
Fallout3
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout3.dll
----------------------------------------
GamebryoBase
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/GamebryoBase.DLL
----------------------------------------
Commanding
    Assembly Version: 1.1.6200.23533
    Win32 Version: 1.1.6200.23533
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/Commanding.DLL
----------------------------------------
Fallout3.XmlScript
    Assembly Version: 1.1.6200.23536
    Win32 Version: 1.1.6200.23536
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout3.XmlScript.dll
----------------------------------------
Fallout4.CSharpScript
    Assembly Version: 1.1.6200.23537
    Win32 Version: 1.1.6200.23537
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout4.CSharpScript.dll
----------------------------------------
Fallout4
    Assembly Version: 1.1.6200.23536
    Win32 Version: 1.1.6200.23536
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout4.dll
----------------------------------------
Fallout4.XmlScript
    Assembly Version: 1.1.6200.23537
    Win32 Version: 1.1.6200.23537
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout4.XmlScript.dll
----------------------------------------
FalloutNV.CSharpScript
    Assembly Version: 1.1.6200.23537
    Win32 Version: 1.1.6200.23537
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/FalloutNV.CSharpScript.dll
----------------------------------------
FalloutNV
    Assembly Version: 1.1.6200.23535
    Win32 Version: 1.1.6200.23535
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/FalloutNV.dll
----------------------------------------
FalloutNV.XmlScript
    Assembly Version: 1.1.6200.23537
    Win32 Version: 1.1.6200.23537
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/FalloutNV.XmlScript.dll
----------------------------------------
Grimrock
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Grimrock.dll
----------------------------------------
Morrowind
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Morrowind.dll
----------------------------------------
NoMansSky
    Assembly Version: 1.1.6200.23539
    Win32 Version: 1.1.6200.23539
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/NoMansSky.dll
----------------------------------------
Oblivion
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Oblivion.dll
----------------------------------------
Skyrim.CSharpScript
    Assembly Version: 1.1.6200.23537
    Win32 Version: 1.1.6200.23537
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Skyrim.CSharpScript.dll
----------------------------------------
Skyrim
    Assembly Version: 1.1.6200.23535
    Win32 Version: 1.1.6200.23535
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Skyrim.dll
----------------------------------------
Skyrim.XmlScript
    Assembly Version: 1.1.6200.23537
    Win32 Version: 1.1.6200.23537
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Skyrim.XmlScript.dll
----------------------------------------
SkyrimSE.CSharpScript
    Assembly Version: 1.1.6200.23537
    Win32 Version: 1.1.6200.23537
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/SkyrimSE.CSharpScript.dll
----------------------------------------
SkyrimSE
    Assembly Version: 1.1.6200.23536
    Win32 Version: 1.1.6200.23536
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/SkyrimSE.dll
----------------------------------------
SkyrimSE.XmlScript
    Assembly Version: 1.1.6200.23537
    Win32 Version: 1.1.6200.23537
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/SkyrimSE.XmlScript.dll
----------------------------------------
Starbound
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Starbound.dll
----------------------------------------
StateOfDecay
    Assembly Version: 1.1.6200.23539
    Win32 Version: 1.1.6200.23539
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/StateOfDecay.dll
----------------------------------------
TESO
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/TESO.dll
----------------------------------------
WarThunder
    Assembly Version: 1.1.6200.23535
    Win32 Version: 1.1.6200.23535
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/WarThunder.dll
----------------------------------------
Witcher2
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Witcher2.dll
----------------------------------------
Witcher3
    Assembly Version: 1.1.6200.23535
    Win32 Version: 1.1.6200.23535
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Witcher3.dll
----------------------------------------
WorldOfTanks
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/WorldOfTanks.dll
----------------------------------------
XCOM2
    Assembly Version: 1.1.5975.32869
    Win32 Version: 1.1.5975.32869
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/XCOM2.dll
----------------------------------------
XRebirth
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/XRebirth.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Scripting
    Assembly Version: 1.1.6200.23533
    Win32 Version: 1.1.6200.23533
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/Scripting.DLL
----------------------------------------
Mods
    Assembly Version: 1.1.6200.23533
    Win32 Version: 1.1.6200.23533
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/Mods.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Antlr3.Runtime
    Assembly Version: 3.4.1.9004
    Win32 Version: 3.4.1.9004
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/Antlr3.Runtime.dll
----------------------------------------
AntlrUtil
    Assembly Version: 1.1.6200.23533
    Win32 Version: 1.1.6200.23533
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/AntlrUtil.dll
----------------------------------------
CSharpScript
    Assembly Version: 1.1.6200.23533
    Win32 Version: 1.1.6200.23533
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/CSharpScript.dll
----------------------------------------
ModScript
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/ModScript.dll
----------------------------------------
XmlScript
    Assembly Version: 1.1.6200.23534
    Win32 Version: 1.1.6200.23534
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/XmlScript.dll
----------------------------------------
ICSharpCode.TextEditor
    Assembly Version: 3.2.1.6466
    Win32 Version: 3.2.1.6466
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ICSharpCode.TextEditor.DLL
----------------------------------------
FOMod
    Assembly Version: 1.1.6200.23533
    Win32 Version: 1.1.6200.23533
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ModFormats/FOMod.dll
----------------------------------------
Transactions
    Assembly Version: 1.1.6185.26943
    Win32 Version: 1.1.6185.26943
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/Transactions.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.17873
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ObjectListView.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.ServiceModel.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Web/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Web.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ServiceModel.Channels
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by DontBlnkBadWolf** [comment]
Check again today, same error not letting me log in. I think it's still letting me download a mod, but I'll have to check when I have more time to do so.

**Comment by DontBlnkBadWolf** [comment]
It stopped doing it and I updated to the 63.12 NMM. But I still think this should be looked into, so it may be avoided in the future.

Posted new issue with 63.12 build
