### ISSUE TITLE
[64.2][Freeze] Trying to Uninstall Sim Settlements Buildings Preview Mod

### ISSUE THREAD

**Issue by brazenvoid** [Nexus-Mods/Nexus-Mod-Manager#264]
The NMM freezes but does not go into an unresponsive state. What I think is that its trying to show a dialog but the dialog doesn't appear for some reason. The window can't be interacted with and I have to kill the process to get back. 

Edit: So I tried to close it by the taskbar menu and it worked, fortunately it even threw an exception and created a trace log. 

```
Message: 
	Predecessor
Full Trace: 
	System.Exception: Predecessor ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ReorderableListView'.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at Nexus.Client.PluginManagement.UI.PluginManagerControl.ManagedPlugins_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at Nexus.Client.Util.Collections.ThreadSafeObservableList`1.Move(Int32 p_intFromIndex, Int32 p_intToIndex)
   at Nexus.Client.PluginManagement.OrderLog.PluginOrderLog.TransactionEnlistment.Commit()
   at Nexus.Client.PluginManagement.OrderLog.PluginOrderLog.TransactionEnlistment.SetPluginOrder(IList`1 p_lstOrderedPlugins)
   --- End of inner exception stack trace ---
   at Nexus.Client.PluginManagement.OrderLog.PluginOrderLog.TransactionEnlistment.SetPluginOrder(IList`1 p_lstOrderedPlugins)
   at Nexus.Client.PluginManagement.OrderLog.PluginOrderLog.SetPluginOrderIndex(Plugin p_plgPlugin, Int32 p_intNewIndex)
   at Nexus.Client.PluginManagement.PluginManager.AddPlugin(String p_strPluginPath)
   at Nexus.Client.PluginManagement.UI.PluginManagerVM.LoadOrderManager_ExternalPluginAdded(Object sender, EventArgs e)
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.PluginOrderManager.FileWatcherOnCreatedLoose(Object source, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.OnCreated(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
Inner Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ReorderableListView'.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at Nexus.Client.PluginManagement.UI.PluginManagerControl.ManagedPlugins_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at Nexus.Client.Util.Collections.ThreadSafeObservableList`1.Move(Int32 p_intFromIndex, Int32 p_intToIndex)
   at Nexus.Client.PluginManagement.OrderLog.PluginOrderLog.TransactionEnlistment.Commit()
   at Nexus.Client.PluginManagement.OrderLog.PluginOrderLog.TransactionEnlistment.SetPluginOrder(IList`1 p_lstOrderedPlugins)

Running Threads (2)
    8 () 
        Aborted
    15 () 
        Aborted
```

**Comment by jyeary** [comment]
I had the same thing happen. It brought up the progress bar, and I could see the processes consuming CPU and memory. However after 15 minutes I killed it and tried again by disabling and then installing a new version of Sim Settlements. I was then able to uninstall the other version. I wanted to play more than complain at the time so I am sorry to say I didn't capture the logs.

**Comment by brazenvoid** [comment]
For this mod, even disable does the same thing. 

It has many ESPs which it replaces from other sim settlement addon mods, the only thing that I see as the culprit. Those other mods are almost no more now as the sim settlements community released an updated merged mega pack for them. The problem is that when sim settlements detects the old ESPs, it uses those instead. So I wanted the redundant ESPs removed by reinstalling the mod.
