### ISSUE TITLE
NMM won't stop returning "A problem occurred during installation: Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by AHamsterPig** [Nexus-Mods/Nexus-Mod-Manager#282]
I'm following BitRaitBec's modlist and I'm trying to install [Crows and Creatures](https://www.nexusmods.com/fallout4/mods/13488?tab=files) by Xazomn but NMM just refuses to recognize the fomod. It won't hang or install any % of the mod; it goes straight to the error.

**Comment by upular22** [comment]
I'm having the same problem...plz help

**Comment by grimpanda121** [comment]
same problem lol trying to install mods for fallout 4 went and installed version 64.3 instead on 65 and it is working again
went here https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases

**Comment by EyeDeck** [comment]
It looks like what specifically broke with 0.65 was FOMOD handling; any mod with a FOMOD installer just fails with an error. Even if the ModuleConfig.xml file is completely empty, it still errors and fails.

**Comment by AHamsterPig** [comment]
As EyeDeck said, it was a problem with .65 NMM. I ended up just switching to Vortex to continue

**Comment by EyeDeck** [comment]
Per [this post](https://forums.nexusmods.com/index.php?/topic/6588751-security-update-for-nexus-mod-manager/page-5#entry59540366), apparently the problem was that FOMOD installers tend to want to access e.g.
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://qconsulting.ca/fo3/ModConfig5.0.xsd">`
And NMM was upgraded to _only_ support HTTPS, so those URLs trying to access HTTP were causing it to break. It appears that 0.65.1 has corrected this.

**Comment by squid-box** [comment]
Is anyone of you still having this issue on the newer version of NMM?

**Comment by CritLoren** [comment]
I do on the latest version. A lot @squid-box 
I have to disable the mod which removes all installed files, then pick a different FOMOD config so it passes. Some mods don't have different options so I had to resort to manual installation.

**Comment by squid-box** [comment]
@blureshadow: Just to be clear, by latest version you mean [0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest) ?

Could you attach a [trace log](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log) to this issue?

**Comment by CritLoren** [comment]
@squid-box Yes.

> Tracing an Unhandled Exception:
Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.BackgroundTasks.UI.ProgressDialog..ctor(IBackgroundTask p_bgtTask, Boolean p_booAllowCancel)
   at Nexus.Client.ModManagement.UI.ModManagerControl.ViewModel_ActivatingMod(Object sender, EventArgs`1 e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Nexus.Client.ModManagement.UI.ModManagerVM.DisableMods(List`1 p_modMods)
   at Nexus.Client.Commands.Generic.Command`1.Execute(T p_tArgument)
   at Nexus.Client.Commands.Generic.CommandBinding`1.Execute()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Tracing an Unhandled Exception:
Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.BackgroundTasks.UI.ProgressDialog.DoDispose()
   at Nexus.Client.BackgroundTasks.UI.ProgressDialog.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()

I have attached the full tracelog. This time it happened during the install of the XPMSSE 4.33.
[TraceLog20180721190945.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2217434/TraceLog20180721190945.txt)

**Comment by squid-box** [comment]
The TraceLog indicates the crash happeend as NMM was disabling a mod, so I'm not entirely convinced I'm poking at the correct parts, but #521 could make this work a little better.

If you're feeling adventurous you could try the build from [my build machine here](https://build.ahlgren.io/viewLog.html?buildId=280&buildTypeId=GitHub_Nmm_Build&tab=artifacts), otherwise it'll likely be included in the  next release of NMM.
