### ISSUE TITLE
Fallout 4 VR 

### ISSUE THREAD

**Issue by Dantego** [Nexus-Mods/Nexus-Mod-Manager#288]
I installed nmm versio 0.65.2-4-0-65-2 and configured Fallout 4 VR on it to my D:\SteamLibrary\steamapps\common\Fallout 4 VR directory and after clicking OK, then selecting Fallout 4 in the selections and clicking ok it generates the trace file with this:

Determining Game Mode: (From Selection Form) Fallout4
Game Mode Factory Selected: Fallout 4 (Fallout4)
Creating Game Mode mutex (Attempt: 0)

Tracing an Unhandled Exception:
Running Threads (1)
    3 () 
        Aborted
        Exception: 
Message: 
	Value cannot be null.
Parameter name: v1
Full Trace: 
	System.ArgumentNullException: Value cannot be null.
Parameter name: v1
   at System.Version.op_LessThan(Version v1, Version v2)
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.PluginOrderManager.InitializeManager()
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeBase.SetupPluginManagement(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Fallout4.Fallout4GameMode..ctor(IEnvironmentInfo p_eifEnvironmentInfo, FileUtil p_futFileUtility)
   at Nexus.Client.Games.Fallout4.Fallout4GameModeFactory.InstantiateGameMode(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeFactory.BuildGameMode(FileUtil p_futFileUtility, ViewMessage& p_imsWarning)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] p_objArgs)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

I am running windows 10 and this is the first time setting up NMM on this PC.

I uninstalled, reinstalled - same issue. Also tried earlier versions 64.3 and 63.15 with the same results.

**Comment by SolidusBlindSnake** [comment]
Null error solution by Paul mcgoldrick here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/300
