### ISSUE TITLE
SkyUI Installation Using Scripts

### ISSUE THREAD

**Issue by sonic65101** [Nexus-Mods/Nexus-Mod-Manager#380]
Description: Installing SkyUI crashes NMM, this seems to be an ongoing problem with certain mods that use scripts.
Environment:
NMM 0.65.5
Mod: SkyUI (https://www.nexusmods.com/skyrim/mods/3863)

How to Reproduce: Install or re-install SkyUI.

Additional Information:
[TraceLog20180607023834.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2079476/TraceLog20180607023834.txt)
Event Viewer Log (.NET Framework) from the same time:
`Application: NexusClient.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Security.SecurityException
   at System.Security.CodeAccessSecurityEngine.Check(System.Object, System.Threading.StackCrawlMark ByRef, Boolean)
   at System.Security.CodeAccessPermission.Demand()
   at System.Environment.GetCommandLineArgs()
   at Nexus.Client.HeaderlessTextWriterTraceListener.Write(System.String)
   at System.Diagnostics.TraceListener.WriteHeader(System.String, System.Diagnostics.TraceEventType, Int32)
   at System.Diagnostics.TraceListener.TraceEvent(System.Diagnostics.TraceEventCache, System.String, System.Diagnostics.TraceEventType, Int32, System.String, System.Object[])
   at System.Diagnostics.TraceInternal.TraceEvent(System.Diagnostics.TraceEventType, Int32, System.String, System.Object[])
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.WriteLoadOrderTask.WriteLoadOrderFile(System.String, System.String[])
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.WriteLoadOrderTask.DoWork(System.Object[])
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(System.Object)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)`

**Comment by sonic65101** [comment]
I'm using Windows 10, the April update, and following some advice on the Nexus Mods Discord server, I opened Windows Features and turned off .NET Framework 3.5 (includes .NET 2.0 and 3.0) and after restarting my computer, SkyUI installed without a problem.
