### ISSUE TITLE
IPC Access Denied

### ISSUE THREAD

**Issue by myroksoff** [Nexus-Mods/Nexus-Mod-Manager#397]
I've tried installing older versions of NMM and that didn't work. I've tried uninstalling and reinstalling it and it gives me this error.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Failed to create an IPC Port: Access is denied.

Full Trace: 
	System.Runtime.Remoting.RemotingException: Failed to create an IPC Port: Access is denied.

   at System.Runtime.Remoting.Channels.Ipc.IpcServerChannel.StartListening(Object data)
   at Nexus.Client.MessagerServer.InitializeListener(EnvironmentInfo p_eifEnvironmentInfo, IGameModeDescriptor p_gmdGameModeInfo, ModManager p_mmgModManager, MainForm p_frmMainForm)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] p_strArgs)
   at Nexus.Client.Program.Main(String[] p_strArgs)

Running Threads **(0)**

**Comment by neoh4x0r** [comment]
@myroksoff 
Are you running on an account with Administrator privileges or a limited user account ?

It might be that your user account is not included in the `IPC Authorized Users` group.

**Comment by squid-box** [comment]
Closing due to inactivity.
