### ISSUE TITLE
NMM 0.65.6 loads but doesn't show mods/plugin screen

### ISSUE THREAD

**Issue by GamerFoxNeumann** [Nexus-Mods/Nexus-Mod-Manager#403]
Recently getting back to Fallout 4 when, surprise, 0.65.5 is being itself. Now I don't know if this is a bug or anything but whenever I start NMM 0.65.5, the manager loads but it doesn't show the plugin/mod screen. Using my task manager it is still there in the background but the window simply doesn't show up.

**Describe the bug** 
Mod manager window not showing up after loading

**Environment**
- NMM version: 0.65.6
- OS: Windows 10
- Drive NMM is installed on: HDD (D:)
- Mod(s) used: 

<No Trace File Available>

**To Reproduce**
Run NMM, let it load

**Additional information** 
[My Taskmanager Pic](https://orig00.deviantart.net/0c28/f/2018/164/e/7/nmm_0_65_5_problem_pic_by_misterartmaster101-dcebyky.png)

**Comment by neoh4x0r** [comment]
@GamerFoxNeumann 
Do you have any trace log files in your Documents folder under Nexus Mod Manger ?

Run NMM again, and try to attach the latest trace log file.

**Comment by GamerFoxNeumann** [comment]
The only trace log I'll get is via End Tasking the program...

Trace file has been created: TraceLog20180613210048.txt
Mod Manager Version: 0.65.6.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6734.28445, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency XmlScript, Version=1.1.6734.28445, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6734.28445, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency XmlScript, Version=1.1.6734.28445, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6734.28445, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency XmlScript, Version=1.1.6734.28445, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6734.28445, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency XmlScript, Version=1.1.6734.28445, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6734.28445, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency XmlScript, Version=1.1.6734.28445, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Fallout4: Supported
Determining Game Mode: Fallout4
Game Mode Factory Selected: Fallout 4 (Fallout4)
Creating Game Mode mutex (Attempt: 0)
Getting listener on: ipc://Nexus Mod Manager-Fallout4IpcServer/Fallout4Listener
Messaging to bring to front.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Failed to read from an IPC Port: The pipe has been ended.

Full Trace: 
	System.Runtime.Remoting.RemotingException: Failed to read from an IPC Port: The pipe has been ended.


Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Nexus.Client.IMessager.BringToFront()
   at Nexus.Client.Bootstrapper.RunMainForm(String[] p_strArgs)
   at Nexus.Client.Program.Main(String[] p_strArgs)

Running Threads (0)

**Comment by neoh4x0r** [comment]
@GamerFoxNeumann 
@DuskDweller 
@squid-box 

This issue should target NMM 0.65.6 and not 0.65.5

Looking the tracelog....it seems as though the bootstrapper is hanging on 
 msgMessager.BringToFront() in RunMainForm -- RestoreFocus() is failing to activate the mainform's window.  

The window never shows, meaning that some issues is causing the call to Activate() to fail (or to freeze?).

I don't know why this is happening ATM, but I believe that the below is a starting point for debugging this issue.

https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/master/NexusClient/Bootstrapper.cs#L142
https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/master/NexusClient/MessagerServer.cs#L190
https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/master/NexusClient/MainForm.cs#L2897

These changes were added in commit: 608d17d88d788b0639c2d46ab587df7a9a76ea4f

**Comment by GamerFoxNeumann** [comment]
Well, the only coding I've experienced is HTML5 (and I was bad at it) but if I'm looking at these right, ain't these coded in such a way that it would increase the chances of this sort of problem happening?

**Comment by GamerFoxNeumann** [comment]
Well, is there any information on this front, because using the F4SE Loader directly is as tedious as it is annoying. :\
