### ISSUE TITLE
Whenever I try to activate a mod for fallout 4, it says the app needs to close and gives me a trace file

### ISSUE THREAD

**Issue by chas3k** [Nexus-Mods/Nexus-Mod-Manager#410]
Trace File:
Trace file has been created: TraceLog20180615132055.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: Morrowind.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Morrowind.ModScript.dll: cannot find dependency ModScript, Version=1.1.6689.33168, Culture=neutral, PublicKeyToken=null
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Oblivion.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Oblivion.ModScript.dll: cannot find dependency ModScript, Version=1.1.6689.33168, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Oblivion: Supported
    Loading TESO: Supported
    Loading Fallout4: Supported
Determining Game Mode: (From Selection Form) Fallout4
Game Mode Factory Selected: Fallout 4 (Fallout4)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Fallout 4 (Fallout4)
    Installation Path: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4
    Install Info Path: C:\Games\Nexus Mod Manager\Fallout4\Install Info
    Mod Path: C:\Games\Nexus Mod Manager\Fallout4\Mods
    Mod Cache Path: C:\Games\Nexus Mod Manager\Fallout4\Mods\cache
    Mod Download Cache: C:\Games\Nexus Mod Manager\Fallout4\Mods\downloads
    Overwrite Path: C:\Games\Nexus Mod Manager\Fallout4\Install Info\overwrites
    Virtual Install Path: C:\Games\Nexus Mod Manager\Fallout4\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\GameModes
            Checking: Fallout4.CSharpScript.dll
                Initializing: Nexus.Client.Games.Fallout4.Scripting.CSharpScript.Fallout4CSharpScriptType
            Checking: Fallout4.XmlScript.dll
                Initializing: Nexus.Client.Games.Fallout4.Scripting.XmlScript.Fallout4XmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Program Files\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: C:\Games\Nexus Mod Manager\Fallout4\Mods
        Found: C:\Games\Nexus Mod Manager\Fallout4\Mods\Start Me Up - Normal Dialogue Prompts - version 6.1-18946-6-1.zip
            Registered.
    Found 1 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: C:\Games\Nexus Mod Manager\Fallout4\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data
                Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\3dscopes.esp
                Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\dd-enhanced blood basic.esp
                Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\Fallout4.esm
            Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\3dscopes.esp
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\dd-enhanced blood basic.esp
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\Fallout4.esm
                Registered.
        Found 3 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\Fallout4.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\3dscopes.esp (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\dd-enhanced blood basic.esp (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Fallout4.exe (IsNull=False)
    SKSE Command: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\f4se_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    LOOT Command:  (IsNull=True)
    FO4Edit Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
Loading Plugins into Plugin List: 3
    Loading: Fallout4.esm (C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\Fallout4.esm) (False)
    Loading: 3dscopes.esp (C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\3dscopes.esp) (False)
    Loading: dd-enhanced blood basic.esp (C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\dd-enhanced blood basic.esp) (False)
Setting up listener on Nexus Mod Manager-Fallout4IpcServer/Fallout4Listener at 2018-06-15 13:21:08
Running Application.

Tracing an Unhandled Exception:
Exception: 
Message: 
	The cloud file provider is not running.

Full Trace: 
	System.IO.IOException: The cloud file provider is not running.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at Nexus.Client.Games.Fallout4.Tools.GamebryoIniReader.set_IniFile(String value)
   at Nexus.Client.Games.Fallout4.Fallout4GameMode.RequiresExternalConfig(String& p_strMessage)
   at Nexus.Client.ModManagement.UI.ModManagerVM.ActivateMods(List`1 p_lstMod)
   at Nexus.Client.Commands.Generic.Command`1.Execute(T p_tArgument)
   at Nexus.Client.Commands.Generic.CommandBinding`1.Execute()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Running Threads (0)

**Comment by Schtroumpf9** [comment]
Yeah, I have the exact same issue. I'm assuming it's server related, as I get an error when checking for updates too.

**Comment by Schtroumpf9** [comment]
So I figured out my issue was because I didn't have OneDrive running.

**Comment by squid-box** [comment]
A guess from some Googling: the files NMM is trying to access are stored in a folder synced through OneDrive, but it's not running (as mentioned above) - either you have to have OneDrive running, or set that folder to always be locally available.

@chas3k - did you try it it solved your problem?

**Comment by squid-box** [comment]
Closing issue due to inactivity.

**Comment by zp3nz3r** [comment]
Having the same issue

**Comment by squid-box** [comment]
@zp3nz3r: And have you tried what I suggested in my previous comment about OneDrive above?
