### ISSUE TITLE
NMM add mod from file not working

### ISSUE THREAD

**Issue by xDanny15** [Nexus-Mods/Nexus-Mod-Manager#421]
**Describe the bug** 
every time i clicked it, it shows an trace error when i research the error the result is about Visual Studio and C#. I try updating and reinstalling but nothing work.. 

Tracing an Unhandled Exception:
Exception: 
Message: 
	Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (Exception from HRESULT: 0x80040111 (CLASS_E_CLASSNOTAVAILABLE)).
Full Trace: 
	System.Runtime.InteropServices.COMException (0x80040111): Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (Exception from HRESULT: 0x80040111 (CLASS_E_CLASSNOTAVAILABLE)).
   at System.Windows.Forms.OpenFileDialog.CreateVistaDialog()
   at System.Windows.Forms.FileDialog.RunDialogVista(IntPtr hWndOwner)
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at Nexus.Client.ModManagement.UI.ModManagerControl.addModToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Running Threads (0)

**Environment**
- NMM version: 0.65.6
- Mod(s) used: Nexus Mod Manager

**Additional information** 
just trying to to install mods for the first time can't put skse on skyrim

[TraceLog20180619140640.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2115311/TraceLog20180619140640.txt)

**Comment by squid-box** [comment]
According to [this SO answer](https://stackoverflow.com/a/34246500/1728343), it seems likely there's something odd about your computer setup. The crash is happening when NMM tries to show Windows standard file selection dialog.

According to that SO post it could be caused by disabling Visual Themes in Windows - have you done anything like that?

**Comment by squid-box** [comment]
Closing issue due to inactivity.
