### ISSUE TITLE
NMM cannot connect to servers or login

### ISSUE THREAD

**Issue by Acalian** [Nexus-Mods/Nexus-Mod-Manager#551]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
As Stated in title,

login token does not work, attempt to manually log in fails,

get this error report

'Unhandled exception has occured in your application. If you click Continue, the Application will ignore this error and attempt to continue. If you click quit, the application will close imediatley.

Error Creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section'

if i click continue, nothing happens, i can click for more details which are:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Configuration.ConfigurationErrorsException: Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section. ---> System.DllNotFoundException: Unable to load DLL 'rasapi32.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Net.UnsafeNclNativeMethods.RasHelper.RasEnumConnections(RASCONN[] lprasconn, UInt32& lpcb, UInt32& lpcConnections)
   at System.Net.UnsafeNclNativeMethods.RasHelper.GetCurrentConnectoid()
   at System.Net.AutoWebProxyScriptEngine.AutoDetector.Initialize()
   at System.Net.AutoWebProxyScriptEngine.AutoDetector.get_CurrentAutoDetector()
   at System.Net.AutoWebProxyScriptEngine..ctor(WebProxy proxy, Boolean useRegistry)
   at System.Net.WebProxy.UnsafeUpdateFromRegistry()
   at System.Net.Configuration.DefaultProxySectionInternal..ctor(DefaultProxySection section)
   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   at System.Net.WebRequest.get_InternalDefaultWebProxy()
   at System.Net.HttpWebRequest..ctor(Uri uri, ServicePoint servicePoint)
   at System.Net.HttpRequestCreator.Create(Uri Uri)
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at System.ServiceModel.Channels.HttpChannelFactory`1.GetWebRequest(EndpointAddress to, Uri via, NetworkCredential credential, TokenImpersonationLevel impersonationLevel, AuthenticationLevel authenticationLevel, SecurityTokenProviderContainer proxyTokenProvider, SecurityTokenContainer clientCertificateToken, TimeSpan timeout, Boolean isWebSocketRequest)
   at System.ServiceModel.Channels.HttpChannelFactory`1.GetWebRequest(EndpointAddress to, Uri via, SecurityTokenProviderContainer tokenProvider, SecurityTokenProviderContainer proxyTokenProvider, SecurityTokenContainer clientCertificateToken, TimeSpan timeout, Boolean isWebSocketRequest)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.GetWebRequest(EndpointAddress to, Uri via, SecurityTokenContainer clientCertificateToken, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.HttpsChannelFactory`1.HttpsRequestChannel.GetWebRequest(EndpointAddress to, Uri via, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Nexus.Client.ModRepositories.Nexus.INexusModRepositoryApi.LoginPOST(String p_strUsername, String p_strPassword)
   at Nexus.Client.ModRepositories.Nexus.NexusModRepository.Login(String p_strUsername, String p_strPassword, Dictionary`2& p_dicTokens)
   at Nexus.Client.LoginFormVM.Login()
   at Nexus.Client.LoginFormTask.LoginForm_Authenticating(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Nexus.Client.LoginForm.butLogin_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at System.Windows.Forms.Form.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.TextBoxBase.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NexusClient
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/NexusClient.exe
----------------------------------------
Util
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/Util.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NexusClient.Interface
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/NexusClient.Interface.DLL
----------------------------------------
SevenZipSharp
    Assembly Version: 0.64.3890.29348
    Win32 Version: 0.64.3890.29348
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/SevenZipSharp.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
UI
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/UI.DLL
----------------------------------------
ModManager.Interface
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ModManager.Interface.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
BreakingWheel
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/BreakingWheel.dll
----------------------------------------
ChinhDo.Transactions
    Assembly Version: 1.1.0.25
    Win32 Version: 1.1.0.25
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ChinhDo.Transactions.DLL
----------------------------------------
DarkSouls
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DarkSouls.dll
----------------------------------------
DarkSouls2
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DarkSouls2.dll
----------------------------------------
DragonAge
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DragonAge.dll
----------------------------------------
DragonAge2
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DragonAge2.dll
----------------------------------------
DragonsDogma
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/DragonsDogma.dll
----------------------------------------
Fallout3.CSharpScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout3.CSharpScript.dll
----------------------------------------
Fallout3
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout3.dll
----------------------------------------
GamebryoBase
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/GamebryoBase.DLL
----------------------------------------
Commanding
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/Commanding.DLL
----------------------------------------
Fallout3.XmlScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout3.XmlScript.dll
----------------------------------------
AntlrUtil
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/AntlrUtil.DLL
----------------------------------------
Fallout4.CSharpScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout4.CSharpScript.dll
----------------------------------------
Fallout4
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout4.dll
----------------------------------------
Fallout4.XmlScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout4.XmlScript.dll
----------------------------------------
Fallout4VR
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Fallout4VR.dll
----------------------------------------
FalloutNV.CSharpScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/FalloutNV.CSharpScript.dll
----------------------------------------
FalloutNV
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/FalloutNV.dll
----------------------------------------
FalloutNV.XmlScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/FalloutNV.XmlScript.dll
----------------------------------------
Grimrock
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Grimrock.dll
----------------------------------------
Morrowind
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Morrowind.dll
----------------------------------------
Morrowind.ModScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Morrowind.ModScript.dll
----------------------------------------
NoMansSky
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/NoMansSky.dll
----------------------------------------
Oblivion
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Oblivion.dll
----------------------------------------
Oblivion.ModScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Oblivion.ModScript.dll
----------------------------------------
Skyrim.CSharpScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Skyrim.CSharpScript.dll
----------------------------------------
Skyrim
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Skyrim.dll
----------------------------------------
Skyrim.XmlScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Skyrim.XmlScript.dll
----------------------------------------
SkyrimSE.CSharpScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/SkyrimSE.CSharpScript.dll
----------------------------------------
SkyrimSE
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/SkyrimSE.dll
----------------------------------------
SkyrimSE.XmlScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/SkyrimSE.XmlScript.dll
----------------------------------------
SkyrimVR
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/SkyrimVR.dll
----------------------------------------
Starbound
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Starbound.dll
----------------------------------------
StateOfDecay
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/StateOfDecay.dll
----------------------------------------
TESO
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/TESO.dll
----------------------------------------
WarThunder
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/WarThunder.dll
----------------------------------------
Witcher2
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Witcher2.dll
----------------------------------------
Witcher3
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/Witcher3.dll
----------------------------------------
WorldOfTanks
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/WorldOfTanks.dll
----------------------------------------
XCOM2
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/XCOM2.dll
----------------------------------------
XRebirth
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/GameModes/XRebirth.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Scripting
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/Scripting.DLL
----------------------------------------
Mods
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/Mods.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Antlr3.Runtime
    Assembly Version: 3.4.1.9004
    Win32 Version: 3.4.1.9004
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/Antlr3.Runtime.dll
----------------------------------------
CSharpScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/CSharpScript.dll
----------------------------------------
ModScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/ModScript.dll
----------------------------------------
XmlScript
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ScriptTypes/XmlScript.dll
----------------------------------------
ICSharpCode.TextEditor
    Assembly Version: 3.2.1.6466
    Win32 Version: 3.2.1.6466
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ICSharpCode.TextEditor.DLL
----------------------------------------
FOMod
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ModFormats/FOMod.dll
----------------------------------------
Transactions
    Assembly Version: 0.65.9.0
    Win32 Version: 0.65.9.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/Transactions.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.17873
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Program%20Files/Nexus%20Mod%20Manager/ObjectListView.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.ServiceModel.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Web/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Web.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ServiceModel.Channels
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Environment**
- NMM version: _0.65.9_

**Comment by squid-box** [comment]
It looks like something is broken with your Windows installation, the error is:

>System.DllNotFoundException: Unable to load DLL 'rasapi32.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

`rasapi32.dll` is not provided by NMM, it's part of Windows.

From a brief Google search it seems to be a fairly common problem so you might be able to restore it.

**Comment by squid-box** [comment]
Closing due to inactivity.
