### ISSUE TITLE
Cannot add a screenshot

### ISSUE THREAD

**Issue by ccyang1991** [Nexus-Mods/Nexus-Mod-Manager#691]
**Describe the bug** 
Trying to locally add a screenshot, 
Client does not crash, and screenshot is not added

**Environment**
- NMM version: 0.65.11

**To Reproduce**
Any mod -> Get Missing Mod Info (Edit Info) -> Add Screenshot

Trace Log
	System.NullReferenceException: No matches on the Nexus server. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.ModRepositories.Nexus.NexusModRepository.FindMods(String p_strModNameSearchString, Boolean p_booIncludeAllTerms)
   --- End of inner exception stack trace ---
   at Nexus.Client.ModRepositories.Nexus.NexusModRepository.FindMods(String p_strModNameSearchString, Boolean p_booIncludeAllTerms)
   at Nexus.Client.ModManagement.AutoTagger.GetTagInfoCandidates(IMod p_modMod)
Inner Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.ModRepositories.Nexus.NexusModRepository.FindMods(String p_strModNameSearchString, Boolean p_booIncludeAllTerms)

**Comment by squid-box** [comment]
Very little comfort, but with the new Nexus API this issue is outdated. If still a problem please open a new issue.
