### ISSUE TITLE
Unable to start NMM after updating to version 0.65.2.0

### ISSUE THREAD

**Issue by dmille83** [Nexus-Mods/Nexus-Mod-Manager#728]
**Describe the bug** 
Unable to start NMM after updating to version 0.65.2.0 from the previous most recent version.
[TraceLog20190512145642.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3170494/TraceLog20190512145642.txt)

**Environment**
- NMM version: 0.65.2.0

**To Reproduce**
Attempt to start NMM after updating.

**Comment by squid-box** [comment]
I'm not quite sure what the error is caused by, 

```
Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=1.1.6689.33169, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```
you could try to reinstall NMM 0.65.2 and see if that helps.

But note that from tomorrow you'll need to update to 0.70.0 or higher to be able to log in / interact with Nexus (if you're just using NMM as an offline mod manager, that won't matter).

**Comment by Ymirithe** [comment]
updated nmm from 0.65.11 to 0.70.0  and now the software refuse to launch. here is the error log : https://drive.google.com/open?id=1oZ_QsB30M1M7KVmBo_8U3Sw2u9TjUW3D

running as administrator or re-installing does nothing.  
i made sure to white list in defender . then i killed it. killed the file security, the system integrity, the firewall. disabled the real time protection. closed all non-essential software running on my pc. nmm just can't start anymore.

window 10 here.

fix. install the new release in a separate location and set the file-path identical to the previous installation (location of the mod backup and other settings)  so that you can keep your load order.

then locate the folder of the old installation (where the 65.11 .exe is located) and manually delete it.

learning experience. : its impossible to ""update past 0.65.11 ''' 70.0 is a new installation  but the trick above allow to keep your load order

**Comment by yarrmateys** [comment]
the easiest way i found was
1) rename your existing install's folder, for example d:\games\NMM to d:\games\NMM1
2) install update in d:\games\NMM. don't start it yet when it asks.
3) move the folder "Games" and/or any game folders like Fallout4 or Skyrim from old folder to new folder. the folders that hold all the installation info and mods for every game.
and it'll work.

**Comment by squid-box** [comment]
Some questions, if you're in this state:
1. Did you close NMM during the upgrade? (Installer will prompt you to shut down any running instances of NMM)
2. If you go into your installation directory, and look at the properties/details of `GameModes\Fallout3.dll` and `GameModes\Fallout3.XmlScript.dll`, are they both version 0.70.0.0 ?

![image](https://user-images.githubusercontent.com/864820/57600063-fc2ead00-7558-11e9-818b-ee7f6d5362c2.png)


Obviously something is going wrong, but I've had no issue upgrading from 0.65.11 to 0.70.0 - and so far we've had 2678 downloads of 0.70.0.

**Comment by viper1s** [comment]
Instead of an "official" fix I renamed my old NMM install folder (for posterity sake) , did a fresh install of 70 
Worked like a charm
3 minutes and I loaded the new version with everything intact. Now deleting the old install folder
ANd , I must say I like the new load look

**Comment by agentfeenix** [comment]
Having the same issue.  Downloaded new version and it won't load.  Trying to install older version of 0.65.11 now yields the same result.  I shut down NMM during install & both fallout 3 dll & xml are version 0.70.0 in gamemodes folder

 Tracing an Unhandled Exception:
        Exception: 
Message: 
	Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.70.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Full Trace: 
	System.TypeLoadException: Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.70.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo environmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

        Running Threads (0)

**Comment by viper1s** [comment]
There is something left in the old folder that the new version does not like

**Comment by squid-box** [comment]
OK, so not what I'd hoped for. 

I'll try to make some troubleshooting tool tonight, but in the meantime I'd recommend a clean installation - as in uninstall NMM (but keep the config files), ensure that the Program Files folder is removed, then install 0.70.0.

**Comment by agentfeenix** [comment]
for some reason, it also is not detected F4SE.  Functionality was working without a hitch prior to this NMM update;  I have went in to custom launch command and entered F4SE file path manually, closed & restarted NMM and it won't detect F4SE or fallout launcher options.  My only option thru NMM is custom launch option

**Comment by squid-box** [comment]
@agentfeenix: Could you report that as a separate issue? And [force a trace log](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log) to attach to the issue so we can see if anything is going wrong internally.

**Comment by viper1s** [comment]
> 
In my case it showed Skyrim Custom Launcher instead of the SKSE as normal for SSE
When launched from "Custom" , 3 versions of Skyrim SE launched. One plain , the other 2 SKSE enabled

Launching Skyrim SE (Plain)...
    Command: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\SkyrimSE.exe
    Succeeded
Launching Skyrim SE (SKSE)...
    Command: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\skse64_loader.exe
    Succeeded
Launching Skyrim SE (Custom)...
    Succeeded
Running Threads (0)

No Launch options for any Script Extenders are there
The list I have verified
Skyrim SE (SKSE64)
Fallout 4 (FO4SE)
Fallout  NV (NVSE)
Fallout 3 (FOSE)
All 4 reverted to custom launch options

**Comment by GarnetSan** [comment]
Well, I did as some users were suggesting above, and I can confirm that renaming your old folder to keep previous versions then installing 70.3 does work. Problem is, nexusmods.com seems to be down, so I can't download mods rn

**Comment by mrrogers75** [comment]
To fix:
In the Nexus Mod Manager Install folder (default location "Program Files\Nexus Mod Manager") rename the following files if they exist, do not rename any files in the GameModes Folder:
Antlr3.Runtime.dll   to Antlr3.Runtime.old
FalloutNV.dll to Fallout.NV.old
RestSharp.dll to RestSharp.old

Once you have done that run Nexus Mod Manager and see if it works, if it does go ahead and delete the renamed files.

**Comment by JimmyRJump** [comment]
> 
> 
> To fix:
> In the Nexus Mod Manager Install folder (default location "Program Files\Nexus Mod Manager") rename the following files if they exist, do not rename any files in the GameModes Folder:
> Antlr3.Runtime.dll to Antlr3.Runtime.old
> FalloutNV.dll to Fallout.NV.old
> RestSharp.dll to RestSharp.old
> 
> Once you have done that run Nexus Mod Manager and see if it works, if it does go ahead and delete the renamed files.

Thanks for that.  My problem got solved :)

**Comment by CTSB99** [comment]
Thanks from 2025, solved my Cyberpunk Problem
