### ISSUE TITLE
0.70.6 Failed to Open NMM

### ISSUE THREAD

**Issue by Moksha8088** [Nexus-Mods/Nexus-Mod-Manager#791]
Opened to NMM menu, clicked on Skyrim SE to open its NMM page then Tracelog of Doom came up.

**Environment**
- NMM version: _0.70.6

**To Reproduce**
Try to open the game from the NMM menu

**Additional information** 
Virus checker identified Newtonsoft.Json.dll as a virus.  Even with Newtonsoft.Json.dll installed it failed to work.  It is mentioned in the tracelog.

[TraceLog20190518042321.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3193944/TraceLog20190518042321.txt)

**Comment by squid-box** [comment]
Which virus checker it's reporting Newtonsoft.Json as a virus? And what do you mean with "Even with Newtonsoft.Json.dll installed"?

If your antivirus has flagged Newtonsoft as a virus, it's likely blocking that file, and it's no wonder NMM can't start.

**Comment by Moksha8088** [comment]
Turned off the virus checker and ran the install file.  I think it installed right, but this was the result:
[TraceLog20190518083323.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3194164/TraceLog20190518083323.txt)

**Comment by Leningrado8** [comment]
same problem. it was owrking on 70.5 but sicnce I installed 70.6 it don't start.
here what I get

Trace file has been created: TraceLog20190518114904.txt
Mod Manager Version: 0.70.6.0
OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Games\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Skyrim: Supported
    Loading Fallout4: Supported
Determining Game Mode: (From Selection Form) Skyrim
Game Mode Factory Selected: Skyrim (Skyrim)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Skyrim (Skyrim)
    Installation Path: C:\Games\The Elder Scrolls V Skyrim Legendary Edition
    Install Info Path: C:\Games\Nexus Mod Manager\Skyrim\Install Info
    Mod Path: C:\Games\Nexus Mod Manager\Skyrim\Mods
    Mod Cache Path: C:\Games\Nexus Mod Manager\Skyrim\Mods\cache
    Mod Download Cache: C:\Games\Nexus Mod Manager\Skyrim\Mods\downloads
    Overwrite Path: C:\Games\Nexus Mod Manager\Skyrim\Install Info\overwrites
    Virtual Install Path: C:\Games\Nexus Mod Manager\Skyrim\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
    
    Tracing an Unhandled Exception:
    Running Threads (1)
    3 () 
        Aborted
        Exception: 
Message: 
	Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': Não foi possível encontrar o módulo especificado. (Exception from HRESULT: 0x8007007E)
Full Trace: 
	System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': Não foi possível encontrar o módulo especificado. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetNativeSystemInfo(SYSTEM_INFO& lpSystemInfo)
   at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture()
   at Pathoschild.FluentNexus.NexusClient.GetDefaultUserAgent(String appName, String appVersion)
   at Pathoschild.FluentNexus.NexusClient..ctor(String apiKey, String appName, String appVersion, String baseUrl)
   at Nexus.Client.ModRepositories.ApiCallManager.UpdateNexusClient()
   at Nexus.Client.ModRepositories.ApiCallManager.Instance(IEnvironmentInfo environmentInfo)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by Moksha8088** [comment]
Got .70.6 to run.  Comodo AV was to blame.  It fixed the bug from .70.5 of crashing on checking for updates.

**Comment by Moksha8088** [comment]
Comodo detected both the Newtonsoft.json.dll and NMM 0.70.6.  What was needed was to unblock and trust the two files and NMM once again worked and was able to check on updates even for files no longer on the Nexus without crashing.  

Was able to download an updated file without incident.  As Zora Fair-Child would say, "All better now".

**Comment by Leningrado8** [comment]
could you explain how should I proceed ? please. I have no programming Knowledge.

**Comment by Leningrado8** [comment]
I installed 70.7 and it seams to be working now!
