### ISSUE TITLE
NMM Will Not Load ANY Oblivion Mods 

### ISSUE THREAD

**Issue by Sorceress99** [Nexus-Mods/Nexus-Mod-Manager#834]
I have intalled 0.70.7 many times and set if to run as Admin yet it will not load any mods. Crashes with the same trace errors everyone else seems to be having. It did install 2 mods early on but failed to add any mesh or texture files, only the esps. I am running GOG's Oblivion GOTY DLX Edition.  Every mods I try to add has the error and will not install.  Doesn't seem to be any solution as far as I can see. Someone gonna fix the damn thing?   

[file:///G:/NewDL/Apachii_Wigs_MaleFemale_v_1_0-40774-1-0.7z] Adding Mod to AddModQueue
[file:///G:/NewDL/Apachii_Wigs_MaleFemale_v_1_0-40774-1-0.7z] Starting Add Mod Task.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.ModRepositories.NexusModsApiRepository.GetModInfoForFile(String fileName)
   at Nexus.Client.ModManagement.AddModTask.GetModInfo(AddModDescriptor descriptor)
   at Nexus.Client.ModManagement.AddModTask.AddMod(Boolean queued)
   at Nexus.Client.ModManagement.ModManager.AddModQueue.AddMod(Uri p_uriPath, ConfirmOverwriteCallback p_cocConfirmOverwrite)
   at Nexus.Client.Commands.Generic.Command`1.Execute(T p_tArgument)
   at Nexus.Client.ModManagement.UI.ModManagerControl.addModToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by squid-box** [comment]
This was hopefully fixed in #845, please try again when 0.70.8 has been released.
