### ISSUE TITLE
Nexus Mod Manager Community Edition error message immediately after installing

### ISSUE THREAD

**Issue by scalra** [Nexus-Mods/Nexus-Mod-Manager#853]
Installed NMM community edition, was able to successfully boot the program, attempted to download a mod from the Nexus site.  I authorized the new NMM program to access my account. In the bottom left the program displayed "sending log in credentials", which was taking forever, so I closed the program. The next time I tried to boot the program I got an error message with a trace log. I opted to reinstall the whole program. This time I got the error message immediately and haven't been able to access NMM since.  See the trace log excerpt below: 

Scanning for read-only files...
Initializing Mod Repository...
    Running Threads (1)
    3 () 
        Aborted
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Full Trace: 
	System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetNativeSystemInfo(SYSTEM_INFO& lpSystemInfo)
   at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture()
   at Pathoschild.FluentNexus.NexusClient.GetDefaultUserAgent(String appName, String appVersion)
   at Pathoschild.FluentNexus.NexusClient..ctor(String apiKey, String appName, String appVersion, String baseUrl)
   at Nexus.Client.ModRepositories.ApiCallManager.UpdateNexusClient()
   at Nexus.Client.ModRepositories.ApiCallManager.Instance(IEnvironmentInfo environmentInfo)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by squid-box** [comment]
Without the full log I can't tell, but it looks like a problem that was fixed in 0.70.7 - got should grab 0.70.8 from the releases page and this should be fixed.

If you tried to log in yesterday there's a good chance the Nexus servers were down.

**Comment by squid-box** [comment]
Closing due to inactivity.
