### ISSUE TITLE
0.70.8 having issues with Fallout3.xml file, though I don't have that game installed

### ISSUE THREAD

**Issue by bbiller77** [Nexus-Mods/Nexus-Mod-Manager#887]
I was updating NMM it sent word of the update, let it install that and now I get the error for Fallout 3's XML file, though I don't have that game installed. I have tried earlier versions of NMM back to 0.65.10 (next version from my previous) as well as a few of the 70's to no avail. Any ideas welcome as I don't want to reinstall everything. Trace log below:

Start Trace Log

Trace file has been created: TraceLog20190828220825.txt
Mod Manager Version: 0.70.8.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.70.8.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Full Trace: 
	System.TypeLoadException: Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.70.8.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo environmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

        Running Threads (0)

End Trace Log

Hopefully someone has a fix. I have posted this log to the Nexus Forums too in case someone there knows the cause.

**Comment by jbostrus** [comment]
I recall running into this, or atleast a similar issue before. See #728 #761 For brevity the solution is:
1. Make note of where NMM is installed to if different from the default path. This will be needed later.
1. Uninstall NMM. When asked to remove config file choose no.
1. Restart PC to make sure any open file handles locked by NMM were now closed.
1. Manually go look for the install folder where NMM was. Typically "C:\Program Files\Nexus Mod Manager" and remove it if still present. If you had a non standard install location then check that.
1. Restart PC again just to make sure any straggling file handles were closed by Windows and cleaned up.
1. Reinstall NMM to the same place it was.
   * Changing the install location will make it create a new config file and forget about your installed games and mods.

The PC restarts are my own suggestion as sometimes files can remain locked even when trying to uninstall and this alleviates those issues.
