### ISSUE TITLE
Windows 10 one drive access

### ISSUE THREAD

**Issue by Skylord13** [Nexus-Mods/Nexus-Mod-Manager#891]
Whenever I try to "check" the following mod in order to install it [https://www.nexusmods.com/fallout4/mods/27019?tab=files], I get the following issue in my  trace log, and the NMM crashes: "System.IO.IOException: The cloud file provider is not running."
I think this is referring to windows one drive cloud drive, or at least a file access issue. I've tried adding permissions though and have had no luck. I've also tried adding NMM as an exception in my firewall. Any help would be much appreciated.

**Environment**
- NMM version: _0.7.4_
- Mod(s) used: _<https://www.nexusmods.com/fallout4/mods/27019?tab=files>_

Tracelog://

Trace file has been created: TraceLog20190901210221.txt
Mod Manager Version: 0.70.8.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Fallout4: Supported
    Loading XCOM2: Supported
Determining Game Mode: (From Selection Form) Fallout4
Game Mode Factory Selected: Fallout 4 (Fallout4)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Fallout 4 (Fallout4)
    Installation Path: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4
    Install Info Path: C:\Games\Nexus Mod Manager\Fallout4\Install Info
    Mod Path: C:\Games\Nexus Mod Manager\Fallout4\Mods
    Mod Cache Path: C:\Games\Nexus Mod Manager\Fallout4\Mods\cache
    Mod Download Cache: C:\Games\Nexus Mod Manager\Fallout4\Mods\downloads
    Overwrite Path: C:\Games\Nexus Mod Manager\Fallout4\Install Info\overwrites
    Virtual Install Path: C:\Games\Nexus Mod Manager\Fallout4\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\GameModes
            Checking: Fallout4.CSharpScript.dll
                Initializing: Nexus.Client.Games.Fallout4.Scripting.CSharpScript.Fallout4CSharpScriptType
            Checking: Fallout4.XmlScript.dll
                Initializing: Nexus.Client.Games.Fallout4.Scripting.XmlScript.Fallout4XmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Program Files\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: C:\Games\Nexus Mod Manager\Fallout4\Mods
        Found: C:\Games\Nexus Mod Manager\Fallout4\Mods\RAW INPUT - NMM Installer-27019-2-4.zip
            Registered.
    Found 1 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: C:\Games\Nexus Mod Manager\Fallout4\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data
                Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\Fallout4.esm
            Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\Fallout4.esm
                Registered.
        Found 1 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\Fallout4.esm (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Fallout4.exe (IsNull=False)
    SKSE Command: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\f4se_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    LOOT Command:  (IsNull=True)
    FO4Edit Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
Loading Plugins into Plugin List: 1
    Loading: Fallout4.esm (C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\Fallout4.esm) (False)
Setting up listener on Nexus Mod Manager-Fallout4IpcServer/Fallout4Listener at 2019-09-01 21:02:25
Running Application.

Tracing an Unhandled Exception:
Exception: 
Message: 
	The cloud file provider is not running.

Full Trace: 
	System.IO.IOException: The cloud file provider is not running.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at Nexus.Client.Games.Fallout4.Tools.GamebryoIniReader.set_IniFile(String value) in D:\Git-Nexus Mod Manager\Nexus-Mod-Manager\Game Modes\Fallout4\Tools\GamebryoIniReader.cs:line 69
   at Nexus.Client.Games.Fallout4.Fallout4GameMode.RequiresExternalConfig(String& p_strMessage) in D:\Git-Nexus Mod Manager\Nexus-Mod-Manager\Game Modes\Fallout4\Fallout4GameMode.cs:line 290
   at Nexus.Client.ModManagement.UI.ModManagerVM.ActivateMods(List`1 p_lstMod)
   at Nexus.Client.Commands.Generic.Command`1.Execute(T p_tArgument)
   at Nexus.Client.Commands.Generic.CommandBinding`1.Execute()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Running Threads (0)

//

**Comment by TheArcaneBrony** [comment]
that error is related to onedrive, make sure you have it running in the background if you use a microsoft account
