### ISSUE TITLE
NMM crashes on mod install for Fallout New Vegas

### ISSUE THREAD

**Issue by tankslayer367** [Nexus-Mods/Nexus-Mod-Manager#923]
Event Logs

> 

Log Name:      Application
Source:        Application Error
Date:          11/23/2019 10:04:46 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Seans-Desktop
Description:
Faulting application name: NexusClient.exe, version: 0.70.11.0, time stamp: 0x5dd95374
Faulting module name: KERNELBASE.dll, version: 10.0.18362.476, time stamp: 0x83c3d83a
Exception code: 0xe0434352
Fault offset: 0x000000000003a839
Faulting process id: 0x5090
Faulting application start time: 0x01d5a227a50f85f3
Faulting application path: I:\Mod Manager\Nexus Mod Manager\NexusClient.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 40be0b24-b19d-4968-8a58-f91f95f088b1
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-11-23T18:04:46.862872200Z" />
    <EventRecordID>31962</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Seans-Desktop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>NexusClient.exe</Data>
    <Data>0.70.11.0</Data>
    <Data>5dd95374</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.18362.476</Data>
    <Data>83c3d83a</Data>
    <Data>e0434352</Data>
    <Data>000000000003a839</Data>
    <Data>5090</Data>
    <Data>01d5a227a50f85f3</Data>
    <Data>I:\Mod Manager\Nexus Mod Manager\NexusClient.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>40be0b24-b19d-4968-8a58-f91f95f088b1</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
> 
**Second Event log**
> 

Log Name:      Application
Source:        .NET Runtime
Date:          11/23/2019 10:04:46 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Seans-Desktop
Description:
Application: NexusClient.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Security.SecurityException
   at System.Security.CodeAccessSecurityEngine.Check(System.Object, System.Threading.StackCrawlMark ByRef, Boolean)
   at System.Security.CodeAccessPermission.Demand()
   at System.Environment.GetCommandLineArgs()
   at Nexus.Client.HeaderlessTextWriterTraceListener.Write(System.String)
   at System.Diagnostics.TraceListener.WriteHeader(System.String, System.Diagnostics.TraceEventType, Int32)
   at System.Diagnostics.TraceListener.TraceEvent(System.Diagnostics.TraceEventCache, System.String, System.Diagnostics.TraceEventType, Int32, System.String, System.Object[])
   at System.Diagnostics.TraceInternal.TraceEvent(System.Diagnostics.TraceEventType, Int32, System.String, System.Object[])
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.WriteLoadOrderTask.WriteLoadOrderFile(System.String, System.String[])
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.WriteLoadOrderTask.DoWork(System.Object[])
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(System.Object)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-11-23T18:04:46.636012100Z" />
    <EventRecordID>31961</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Seans-Desktop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: NexusClient.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Security.SecurityException
   at System.Security.CodeAccessSecurityEngine.Check(System.Object, System.Threading.StackCrawlMark ByRef, Boolean)
   at System.Security.CodeAccessPermission.Demand()
   at System.Environment.GetCommandLineArgs()
   at Nexus.Client.HeaderlessTextWriterTraceListener.Write(System.String)
   at System.Diagnostics.TraceListener.WriteHeader(System.String, System.Diagnostics.TraceEventType, Int32)
   at System.Diagnostics.TraceListener.TraceEvent(System.Diagnostics.TraceEventCache, System.String, System.Diagnostics.TraceEventType, Int32, System.String, System.Object[])
   at System.Diagnostics.TraceInternal.TraceEvent(System.Diagnostics.TraceEventType, Int32, System.String, System.Object[])
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.WriteLoadOrderTask.WriteLoadOrderFile(System.String, System.String[])
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.WriteLoadOrderTask.DoWork(System.Object[])
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(System.Object)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

</Data>
  </EventData>
</Event>

>

**Comment by tankslayer367** [comment]
This is repeatable too

**Comment by tankslayer367** [comment]
PS The mod that is causing the CTD is MCM
https://www.nexusmods.com/newvegas/mods/42507?tab=files
