### ISSUE TITLE
upgrade nexus mod manager 69 to 70

### ISSUE THREAD

**Issue by madmikem** [Nexus-Mods/Nexus-Mod-Manager#951]
nexus mod manager closes at launch and the following trace log ios submitted:  
Trace file has been created: TraceLog20200105235854.txt
Mod Manager Version: 0.65.9.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.65.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Full Trace: 
	System.TypeLoadException: Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.65.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo p_eifEnvironmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

Please help me get to where I can use nexus mod manager without having to delete any existing mods for fallout 4 and skyrim...thank you

**Comment by Louspirit** [comment]
Same problem here. Problem still showing when reinstalling previous version.
