### ISSUE TITLE
I can still use my mods in game but I cant open the mod manager 

### ISSUE THREAD

**Issue by Koksloks** [Nexus-Mods/Nexus-Mod-Manager#981]
Trace file has been created: TraceLog20200324001207.txt
Mod Manager Version: 0.71.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: MonsterHunterWorld.dll
        Initializing: Nexus.Client.Games.MonsterHunterWorld.MonsterHunterWorldGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Fallout4: Supported
Determining Game Mode: (From Selection Form) Fallout4
Game Mode Factory Selected: Fallout 4 (Fallout4)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Fallout 4 (Fallout4)
    Installation Path: E:\steam folder\steamapps\common\Fallout 4
    Install Info Path: E:\Games\Nexus Mod Manager\Fallout4\Install Info
    Mod Path: C:\Users\oliwe\OneDrive\Documents\My Games\Fallout4
    Mod Cache Path: C:\Users\oliwe\OneDrive\Documents\My Games\Fallout4\cache
    Mod Download Cache: C:\Users\oliwe\OneDrive\Documents\My Games\Fallout4\downloads
    Overwrite Path: E:\Games\Nexus Mod Manager\Fallout4\Install Info\overwrites
    Virtual Install Path: E:\steam folder\steamapps\common\Fallout 4\Data\Fallout 4 mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\GameModes
            Checking: Fallout4.CSharpScript.dll
                Initializing: Nexus.Client.Games.Fallout4.Scripting.CSharpScript.Fallout4CSharpScriptType
            Checking: Fallout4.XmlScript.dll
                Initializing: Nexus.Client.Games.Fallout4.Scripting.XmlScript.Fallout4XmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: E:\steam folder\steamapps\common\Fallout 4\Data\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            
            Tracing an Unhandled Exception:
            Running Threads (1)
    3 () 
        Aborted
        Exception: 
Message: 
	The module was expected to contain an assembly manifest. (Exception from HRESULT: 0x80131018)
Full Trace: 
	System.BadImageFormatException: The module was expected to contain an assembly manifest. (Exception from HRESULT: 0x80131018)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Nexus.Client.Mods.ModFormatRegistry.DiscoverFormats(IModCacheManager p_mcmModCacheManager, List`1 p_lstSupportedFormats, IScriptTypeRegistry p_stgScriptTypeRegistry, String p_strSearchPath)
   at Nexus.Client.ApplicationInitializer.InitializeServices(IGameMode p_gmdGameMode, IModRepository p_mrpModRepository, NexusFileUtil p_nfuFileUtility, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
File Name:	
Fusion Log:

**Comment by Koksloks** [comment]
Ok So I think I found a way to temporary fix my problem 
so basically if someone hs a similar problem just open your data folder for fallout and then you should be able to find NMM community edition file which reinstalls the manager to your pc but saves your mods

**Comment by DuskDweller** [comment]
I think something messed up with your NMM install, reinstalling did the trick.
