### ISSUE TITLE
I might have missed the solution IDK

### ISSUE THREAD

**Issue by VariantSix** [Nexus-Mods/Nexus-Mod-Manager#986]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

Tracing an Unhandled Exception:
Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.ModRepositories.NexusModsApiRepository.GetModInfoForFile(String fileName)
   at Nexus.Client.ModManagement.AddModTask.GetModInfo(AddModDescriptor descriptor)
   at Nexus.Client.ModManagement.AddModTask.AddMod(Boolean queued)
   at Nexus.Client.ModManagement.ModManager.AddModQueue.AddMod(Uri p_uriPath, ConfirmOverwriteCallback p_cocConfirmOverwrite)
   at Nexus.Client.Commands.Generic.Command`1.Execute(T p_tArgument)
   at Nexus.Client.ModManagement.UI.ModManagerControl.addModToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by VariantSix** [comment]
so im not a coder or anything that why i asked for help but is it basically saying its not where i say it is

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
